import type { Business, Review } from "./types"
import { cafeHours, clinicHours, everyday, officeHours, restaurantHours } from "./hours"
import { P } from "./photos"

let reviewSeq = 0
function rv(
  author: string,
  rating: number,
  date: string,
  text: string,
  extra?: Partial<Review>
): Review {
  reviewSeq += 1
  return {
    id: `r${reviewSeq}`,
    author,
    rating,
    date,
    text,
    helpful: extra?.helpful ?? Math.round(rating * 4 + 2),
    photos: extra?.photos,
    visitType: extra?.visitType,
  }
}

export const BUSINESSES: Business[] = [
  {
    slug: "moda-teras-mutfak",
    name: "Moda Teras Mutfak",
    category: "restoranlar",
    subcategory: "Modern Türk mutfağı",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Kadıköy",
    country: "Türkiye",
    address: "Moda Caddesi 48, Kadıköy",
    lat: 40.9812,
    lng: 29.0254,
    phone: "+90 216 555 0148",
    website: "https://modateras.example",
    rating: 4.8,
    reviewCount: 612,
    priceLevel: 3,
    tags: ["teras", "deniz manzarası", "rezervasyon", "romantik"],
    amenities: ["teras", "deniz manzarası", "otopark", "vegan seçenek", "engelli erişimi"],
    description:
      "Marmara manzaralı terasında mevsimsel Anadolu mutfağı. Akşam ışığında rezervasyon dolduğu için yapay zekâ asistanı en uygun saati önerir.",
    hours: restaurantHours(),
    cover: P.terrace,
    photos: [P.terrace, P.resto2, P.dish, P.meze],
    verified: true,
    premium: true,
    services: [
      { id: "tasting", name: "Tadım menüsü (2 kişilik)", durationMin: 120, price: 2800 },
      { id: "table", name: "Terasta masa rezervasyonu", durationMin: 90, price: 0 },
    ],
    reviews: [
      rv("Elif K.", 5, "2026-09-18", "Manzara ve ızgara ahtapot kusursuzdu. Teras için mutlaka rezervasyon.", { visitType: "Akşam yemeği", photos: [P.dish] }),
      rv("Can D.", 4, "2026-08-02", "Fiyatlar orta-üst ama porsiyonlar dürüst. Servis biraz yavaştı.", { visitType: "İş yemeği" }),
      rv("Merve A.", 5, "2026-07-11", "Vegan mezeler şaşırtıcı derecede iyi. Doğum günü için ideal.", { visitType: "Kutlama" }),
    ],
  },
  {
    slug: "karakoy-ocakbasi",
    name: "Karaköy Ocakbaşı 1954",
    category: "restoranlar",
    subcategory: "Kebap & ocakbaşı",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Beyoğlu",
    country: "Türkiye",
    address: "Kemankeş Caddesi 12, Karaköy",
    lat: 41.0231,
    lng: 28.9748,
    phone: "+90 212 555 1954",
    rating: 4.6,
    reviewCount: 1840,
    priceLevel: 2,
    tags: ["kebap", "aile", "geleneksel"],
    amenities: ["aile", "açık mutfak", "alkolsüz"],
    description:
      "Üç kuşaktır aynı kömürde pişen Adana ve kuzu şiş. Tripadvisor tarzı güçlü yorum ekosisteminin yerli karşılığı.",
    hours: restaurantHours(),
    cover: P.kebab,
    photos: [P.kebab, P.resto4, P.meze],
    verified: true,
    premium: false,
    reviews: [
      rv("Hakan Y.", 5, "2026-09-01", "Kıyma kebabı İstanbul'daki en iyi üçliden biri. Sıra normal.", { visitType: "Akşam yemeği" }),
      rv("Lara S.", 4, "2026-06-20", "Gürültülü ama lezzet telafi ediyor. Turist kalabalığı var."),
    ],
  },
  {
    slug: "nisantasi-omakase",
    name: "Nişantaşı Omakase",
    category: "restoranlar",
    subcategory: "Japon / sushi",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Şişli",
    country: "Türkiye",
    address: "Abdi İpekçi Caddesi 31, Nişantaşı",
    lat: 41.0488,
    lng: 28.9942,
    phone: "+90 212 555 0731",
    rating: 4.9,
    reviewCount: 288,
    priceLevel: 4,
    tags: ["omakase", "lüks", "rezervasyon"],
    amenities: ["rezervasyon zorunlu", "şarap eşleştirme"],
    description:
      "On kişilik tezgâh, günlük balık. Yüksek reputasyon puanı ve fotoğraflı yorumlarla öne çıkar.",
    hours: {
      pazartesi: { open: "18:00", close: "23:00" },
      sali: { open: "18:00", close: "23:00" },
      carsamba: { open: "18:00", close: "23:00" },
      persembe: { open: "18:00", close: "23:00" },
      cuma: { open: "18:00", close: "23:30" },
      cumartesi: { open: "18:00", close: "23:30" },
      pazar: { open: "00:00", close: "00:00", closed: true },
    },
    cover: P.sushi,
    photos: [P.sushi, P.resto1, P.resto3],
    verified: true,
    premium: true,
    services: [{ id: "oma", name: "Omakase (12 tabak)", durationMin: 120, price: 4200 }],
    reviews: [
      rv("Deniz T.", 5, "2026-09-28", "Hamachi ve wagyu tatlısı unutulmaz. Fiyatına değer.", { visitType: "Özel gün" }),
      rv("Selin B.", 5, "2026-05-14", "Şefle sohbet menünün parçası. Sessiz, dikkatli servis."),
    ],
  },
  {
    slug: "alsancak-pizza-forno",
    name: "Forno Alsancak",
    category: "restoranlar",
    subcategory: "Pizza",
    city: "İzmir",
    citySlug: "izmir",
    district: "Konak",
    country: "Türkiye",
    address: "Kıbrıs Şehitleri Caddesi 88, Alsancak",
    lat: 38.4386,
    lng: 27.1442,
    phone: "+90 232 555 0088",
    rating: 4.5,
    reviewCount: 940,
    priceLevel: 2,
    tags: ["pizza", "teras", "aile"],
    amenities: ["teras", "çocuk menüsü", "gluten-free"],
    description: "Odun fırınında Napoli hamuru, İzmir otlarıyla. Aile masaları ve gluten-free seçenek.",
    hours: restaurantHours(),
    cover: P.pizza,
    photos: [P.pizza, P.terrace, P.resto2],
    verified: true,
    premium: false,
    reviews: [
      rv("Ece N.", 5, "2026-08-22", "Diavola tam kıvamında. Teras yazın doluyor, erken gidin."),
      rv("Barış K.", 4, "2026-04-03", "Gluten-free pizza gerçekten yenilebilir, nadir."),
    ],
  },
  {
    slug: "cankaya-sofrasi",
    name: "Çankaya Sofrası",
    category: "restoranlar",
    subcategory: "Ev yemekleri",
    city: "Ankara",
    citySlug: "ankara",
    district: "Çankaya",
    country: "Türkiye",
    address: "Tunalı Hilmi Caddesi 66",
    lat: 39.9084,
    lng: 32.8601,
    phone: "+90 312 555 0066",
    rating: 4.4,
    reviewCount: 510,
    priceLevel: 1,
    tags: ["ekonomik", "öğle", "ev yemeği"],
    amenities: ["öğle menüsü", "vejetaryen"],
    description: "Günlük tencere yemekleri, esnaf lokantası düzeni. Öğle arası için yapay zekâ 'açık ve ucuz' filtresinde birinci.",
    hours: {
      ...officeHours(),
      cumartesi: { open: "11:00", close: "16:00" },
    },
    cover: P.meze,
    photos: [P.meze, P.resto4],
    verified: true,
    premium: false,
    reviews: [
      rv("Ayşe G.", 5, "2026-09-04", "Kuru fasulye-pilav öğle için birebir. Fiyat dürüst."),
      rv("Onur P.", 4, "2026-03-12", "Sıra oluyor, paket seçeneği kurtarıyor."),
    ],
  },
  {
    slug: "kadikoy-filtre",
    name: "Filtre Kadıköy",
    category: "kafeler",
    subcategory: "Third wave kahve",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Kadıköy",
    country: "Türkiye",
    address: "Yasa Sokak 7, Caferağa",
    lat: 40.9881,
    lng: 29.0241,
    phone: "+90 216 555 0007",
    rating: 4.7,
    reviewCount: 1288,
    priceLevel: 2,
    tags: ["kahve", "laptop", "filtre"],
    amenities: ["wifi", "laptop dostu", "vegan süt"],
    description: "Tek köken filtre ve sessiz arka oda. Yakınımda aramada Kadıköy'ün en yüksek kahve puanı.",
    hours: cafeHours(),
    cover: P.cafe1,
    photos: [P.cafe1, P.coffee, P.cafe2],
    verified: true,
    premium: true,
    reviews: [
      rv("İrem S.", 5, "2026-09-12", "Kenya filtre berrak. Priz çok, toplantı için ideal.", { visitType: "Çalışma" }),
      rv("Emre A.", 4, "2026-07-01", "Öğleden sonra dolu. Sabah 9'da yer bulunur."),
    ],
  },
  {
    slug: "besiktas-firin",
    name: "Beşiktaş Çekirdek Fırın",
    category: "kafeler",
    subcategory: "Fırın & kahvaltı",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Beşiktaş",
    country: "Türkiye",
    address: "Köyiçi Sokak 14",
    lat: 41.0439,
    lng: 29.0058,
    phone: "+90 212 555 0014",
    rating: 4.6,
    reviewCount: 760,
    priceLevel: 2,
    tags: ["kahvaltı", "ekmek", "tatlı"],
    amenities: ["kahvaltı", "paket"],
    description: "Ekşi maya ve menemen. Hafta sonu kuyruğu ünlü; asistan alternatif saat önerir.",
    hours: everyday("07:30", "20:00"),
    cover: P.bakery,
    photos: [P.bakery, P.cafe2, P.coffee],
    verified: true,
    premium: false,
    reviews: [
      rv("Zeynep L.", 5, "2026-08-30", "Poğaça ve filtresi efsane. 08:00'de gidin."),
      rv("Kaan R.", 4, "2026-05-19", "Oturma alanı dar, paket daha mantıklı."),
    ],
  },
  {
    slug: "antalyalight-kahve",
    name: "Lara Light Kahve",
    category: "kafeler",
    subcategory: "Sahil kafe",
    city: "Antalya",
    citySlug: "antalya",
    district: "Muratpaşa",
    country: "Türkiye",
    address: "Lara Caddesi 102",
    lat: 36.8552,
    lng: 30.8154,
    phone: "+90 242 555 0102",
    rating: 4.3,
    reviewCount: 334,
    priceLevel: 2,
    tags: ["sahil", "kahve", "tatil"],
    amenities: ["teras", "deniz manzarası", "wifi"],
    description: "Lara sahilinde soğuk brew ve dondurma. Seyahat aramalarında öne çıkar.",
    hours: everyday("08:00", "23:00"),
    cover: P.cafe2,
    photos: [P.cafe2, P.terrace, P.coffee],
    verified: false,
    premium: false,
    reviews: [rv("Nina M.", 4, "2026-07-08", "Tatilde serinlemek için iyi. Servis yazın yavaş.")],
  },
  {
    slug: "uskudar-makas",
    name: "Üsküdar Makas Atölye",
    category: "guzellik",
    subcategory: "Kuaför",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Üsküdar",
    country: "Türkiye",
    address: "Hakimiyeti Milliye Caddesi 55",
    lat: 41.0249,
    lng: 29.0156,
    phone: "+90 216 555 0055",
    rating: 4.8,
    reviewCount: 421,
    priceLevel: 2,
    tags: ["saç", "randevu", "renk"],
    amenities: ["randevu", "organik ürün"],
    description: "Booksy mantığı: hizmet, süre, fiyat ve uygun slot tek ekranda. Balayage için 3 haftalık doluluk.",
    hours: clinicHours(),
    cover: P.salon,
    photos: [P.salon, P.hair, P.nails],
    verified: true,
    premium: true,
    services: [
      { id: "cut", name: "Kadın kesim + fön", durationMin: 60, price: 950 },
      { id: "color", name: "Tek renk boya", durationMin: 120, price: 2200 },
      { id: "bala", name: "Balayage", durationMin: 180, price: 3800 },
    ],
    staff: [
      { id: "s1", name: "Duygu", role: "Renk uzmanı" },
      { id: "s2", name: "Mert", role: "Kesim" },
    ],
    reviews: [
      rv("Ceren Y.", 5, "2026-09-09", "Balayage doğal durdu. Randevu sistemi sürtünmesiz.", { photos: [P.hair] }),
      rv("Pelin T.", 4, "2026-06-02", "Fiyat şeffaf, sürpriz yok. Otopark yok."),
    ],
  },
  {
    slug: "levent-barber",
    name: "Levent Gentleman Barber",
    category: "guzellik",
    subcategory: "Berber",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Beşiktaş",
    country: "Türkiye",
    address: "Levent Mahallesi, Nispetiye 18",
    lat: 41.0802,
    lng: 29.0144,
    phone: "+90 212 555 0018",
    rating: 4.7,
    reviewCount: 890,
    priceLevel: 3,
    tags: ["berber", "sakal", "randevu"],
    amenities: ["randevu", "içecek", "vale"],
    description: "Fade, sakal ve sıcak havlu. İş dünyası öğle arasına 30 dakikalık slotlar.",
    hours: everyday("10:00", "21:00"),
    cover: P.barber,
    photos: [P.barber, P.salon],
    verified: true,
    premium: true,
    services: [
      { id: "fade", name: "Kesim + fade", durationMin: 45, price: 750 },
      { id: "beard", name: "Sakal + cilt bakımı", durationMin: 30, price: 450 },
    ],
    staff: [
      { id: "s1", name: "Arda", role: "Usta" },
      { id: "s2", name: "Yusuf", role: "Usta" },
    ],
    reviews: [
      rv("Burak E.", 5, "2026-09-21", "Öğle arası 12:40 slotu hayat kurtarıyor."),
      rv("Tolga Ş.", 5, "2026-04-17", "Sakal tıraşı simetrik, ürün satışı baskısız."),
    ],
  },
  {
    slug: "spa-ciragan",
    name: "Çırağan Hamam Spa",
    category: "guzellik",
    subcategory: "Spa & hamam",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Beşiktaş",
    country: "Türkiye",
    address: "Çırağan Caddesi 32",
    lat: 41.0451,
    lng: 29.0176,
    phone: "+90 212 555 0032",
    rating: 4.9,
    reviewCount: 210,
    priceLevel: 4,
    tags: ["spa", "hamam", "lüks"],
    amenities: ["hamam", "masaj", "çift bakımı"],
    description: "Tarihi hamam ritüeli ve aromaterapi. Seyahat + bakım aramalarında önerilir.",
    hours: everyday("10:00", "22:00"),
    cover: P.spa,
    photos: [P.spa, P.hotel],
    verified: true,
    premium: true,
    services: [
      { id: "hamam", name: "Kese + köpük + yağ masajı", durationMin: 90, price: 3200 },
      { id: "couple", name: "Çift ritüeli", durationMin: 120, price: 6400 },
    ],
    reviews: [
      rv("Amelia R.", 5, "2026-08-11", "Hamam taşları gerçek, turistik değil. Rezervasyon şart."),
    ],
  },
  {
    slug: "atasehir-tesisat",
    name: "Ataşehir Hızlı Tesisat",
    category: "ev-hizmetleri",
    subcategory: "Tesisatçı",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Ataşehir",
    country: "Türkiye",
    address: "Ataşehir Bulvarı 12",
    lat: 40.9924,
    lng: 29.1228,
    phone: "+90 216 555 1212",
    rating: 4.6,
    reviewCount: 318,
    priceLevel: 2,
    tags: ["tesisat", "acil", "teklif"],
    amenities: ["acil servis", "fatura", "garanti"],
    description: "Thumbtack tarzı: ihtiyacı yazın, 15 dakikada fiyat aralığı ve müsait usta gelir.",
    hours: everyday("07:00", "23:00"),
    cover: P.plumber,
    photos: [P.plumber, P.tools],
    verified: true,
    premium: true,
    quoteEnabled: true,
    reviews: [
      rv("Gülşah M.", 5, "2026-09-03", "Gece 22:00 kombi arızasında 40 dakikada geldiler. Fiyat önceden net."),
      rv("Serkan U.", 4, "2026-02-14", "Su kaçağı tespiti doğru. Temizlik sonra biraz aceleydi."),
    ],
  },
  {
    slug: "ankara-boya-usta",
    name: "Başkent Boya & Tadilat",
    category: "ev-hizmetleri",
    subcategory: "Boya badana",
    city: "Ankara",
    citySlug: "ankara",
    district: "Yenimahalle",
    country: "Türkiye",
    address: "İvedik Organize 4. Cadde 18",
    lat: 39.9662,
    lng: 32.7451,
    phone: "+90 312 555 0418",
    rating: 4.5,
    reviewCount: 190,
    priceLevel: 2,
    tags: ["boya", "tadilat", "teklif"],
    amenities: ["keşif ücretsiz", "sigortalı ekip"],
    description: "HomeAdvisor mantığı: metrekare ve oda sayısına göre 3 kademeli teklif.",
    hours: officeHours(),
    cover: P.paint,
    photos: [P.paint, P.tools, P.interior],
    verified: true,
    premium: false,
    quoteEnabled: true,
    reviews: [
      rv("Nilüfer A.", 5, "2026-06-28", "3+1 daire iki günde bitti. Koku az, koruma bandı düzgün."),
    ],
  },
  {
    slug: "izmir-temizlik",
    name: "Ege Temiz Ev",
    category: "ev-hizmetleri",
    subcategory: "Temizlik",
    city: "İzmir",
    citySlug: "izmir",
    district: "Karşıyaka",
    country: "Türkiye",
    address: "Cemal Gürsel Caddesi 210",
    lat: 38.4558,
    lng: 27.1114,
    phone: "+90 232 555 0210",
    rating: 4.7,
    reviewCount: 540,
    priceLevel: 2,
    tags: ["temizlik", "taahhüt", "teklif"],
    amenities: ["malzeme dahil", "sigortalı"],
    description: "TaskRabbit gibi: ihtiyaç → uzman → fiyat → işlem. Haftalık abonelik seçeneği var.",
    hours: officeHours(),
    cover: P.clean,
    photos: [P.clean],
    verified: true,
    premium: true,
    quoteEnabled: true,
    services: [
      { id: "std", name: "Standart ev temizliği (2+1)", durationMin: 180, price: 1400 },
      { id: "deep", name: "Derin temizlik", durationMin: 300, price: 2400 },
    ],
    reviews: [
      rv("Fatma K.", 5, "2026-09-14", "Buzdolabı arkası dahil derin temizlik. Fotoğraflı teslim."),
      rv("Ozan B.", 4, "2026-01-22", "Randevu saati 20 dk kaydı, iş kalitesi yüksekti."),
    ],
  },
  {
    slug: "bursa-peyzaj",
    name: "Osmangazi Peyzaj",
    category: "ev-hizmetleri",
    subcategory: "Bahçe & peyzaj",
    city: "Bursa",
    citySlug: "bursa",
    district: "Osmangazi",
    country: "Türkiye",
    address: "Çekirge Caddesi 77",
    lat: 40.2018,
    lng: 29.0442,
    phone: "+90 224 555 0077",
    rating: 4.4,
    reviewCount: 96,
    priceLevel: 3,
    tags: ["bahçe", "peyzaj", "teklif"],
    amenities: ["keşif", "sulama sistemi"],
    description: "Villa bahçesi, otomatik sulama ve mevsimlik dikim. Houzz benzeri görsel portföy.",
    hours: officeHours(),
    cover: P.garden,
    photos: [P.garden, P.interior],
    verified: true,
    premium: false,
    quoteEnabled: true,
    reviews: [rv("Mehmet R.", 4, "2026-05-05", "Sulama otomasyonu sorunsuz. Fide seçiminde sabırlılar.")],
  },
  {
    slug: "kadikoy-dis",
    name: "Moda Diş Kliniği",
    category: "saglik",
    subcategory: "Diş hekimi",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Kadıköy",
    country: "Türkiye",
    address: "Bahariye Caddesi 41",
    lat: 40.9874,
    lng: 29.0288,
    phone: "+90 216 555 0041",
    rating: 4.8,
    reviewCount: 670,
    priceLevel: 3,
    tags: ["diş", "implant", "randevu"],
    amenities: ["randevu", "sedasyon", "3D tomografi"],
    description: "İmplant ve estetik. Randevu takvimi açık, fiyat aralıkları profilde yazılı.",
    hours: clinicHours(),
    cover: P.dental,
    photos: [P.dental, P.clinic],
    verified: true,
    premium: true,
    services: [
      { id: "exam", name: "Muayene + panoramik", durationMin: 30, price: 750 },
      { id: "clean", name: "Diş taşı temizliği", durationMin: 45, price: 1200 },
      { id: "whitening", name: "Ofis tipi beyazlatma", durationMin: 60, price: 4500 },
    ],
    staff: [{ id: "s1", name: "Dr. Aylin Koç", role: "Ortodonti" }],
    reviews: [
      rv("Seda H.", 5, "2026-08-16", "Ağrısız temizlik, net anlatım. Randevu SMS ile hatırlatıldı."),
      rv("Kemal V.", 5, "2026-03-09", "İmplant süreci şeffaf. Toplam maliyet baştan söylendi."),
    ],
  },
  {
    slug: "cankaya-fizik",
    name: "Çankaya Fizik Tedavi",
    category: "saglik",
    subcategory: "Fizyoterapi",
    city: "Ankara",
    citySlug: "ankara",
    district: "Çankaya",
    country: "Türkiye",
    address: "Gaziosmanpaşa, Bestekar Sokak 9",
    lat: 39.8975,
    lng: 32.8684,
    phone: "+90 312 555 0009",
    rating: 4.6,
    reviewCount: 154,
    priceLevel: 2,
    tags: ["fizik tedavi", "spor", "randevu"],
    amenities: ["randevu", "manuel terapi"],
    description: "Spor yaralanmaları ve ofis duruşu. Seans paketleri randevu motoruna bağlı.",
    hours: clinicHours(),
    cover: P.clinic,
    photos: [P.clinic, P.gym],
    verified: true,
    premium: false,
    services: [
      { id: "seans", name: "Manuel terapi seansı", durationMin: 50, price: 1100 },
    ],
    reviews: [rv("Cemre D.", 5, "2026-07-21", "Bel ağrım 6 seansda ciddi azaldı. Ev egzersizi verdiler.")],
  },
  {
    slug: "sisli-performans",
    name: "Şişli Performans Lab",
    category: "saglik",
    subcategory: "Spor salonu",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Şişli",
    country: "Türkiye",
    address: "Halaskargazi Caddesi 120",
    lat: 41.0576,
    lng: 28.9871,
    phone: "+90 212 555 0120",
    rating: 4.5,
    reviewCount: 402,
    priceLevel: 3,
    tags: ["gym", "pt", "randevu"],
    amenities: ["duş", "PT", "otopark"],
    description: "Küçük grup ve kişisel antrenman. Deneme dersi randevu ile.",
    hours: everyday("06:30", "22:30"),
    cover: P.gym,
    photos: [P.gym],
    verified: true,
    premium: false,
    services: [
      { id: "pt", name: "Kişisel antrenman (60 dk)", durationMin: 60, price: 1300 },
      { id: "trial", name: "Deneme dersi", durationMin: 45, price: 0 },
    ],
    reviews: [rv("Ali N.", 4, "2026-09-02", "PT kadrosu güçlü, soyunma biraz dar.")],
  },
  {
    slug: "marmara-dis-ticaret",
    name: "Marmara Dış Ticaret A.Ş.",
    category: "b2b",
    subcategory: "İhracat / ithalat",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Şişli",
    country: "Türkiye",
    address: "Büyükdere Caddesi 201, Levent",
    lat: 41.0814,
    lng: 29.0112,
    phone: "+90 212 555 0201",
    website: "https://marmaradisticaret.example",
    rating: 4.4,
    reviewCount: 38,
    priceLevel: 3,
    tags: ["ihracat", "gıda", "b2b"],
    amenities: ["ihracat belgesi", "ISO 22000"],
    description:
      "Dun & Bradstreet ve Kompass'tan ilham: çalışan sayısı, sektör, ihracat pazarları ve ticari istihbarat kartı.",
    hours: officeHours(),
    cover: P.office,
    photos: [P.office, P.warehouse],
    verified: true,
    premium: true,
    intel: {
      founded: 1998,
      employees: "120–180",
      industry: "Gıda ihracatı",
      revenue: "€42M (2025)",
      taxId: "VKN 1234567890",
      exportMarkets: ["Almanya", "Hollanda", "BAE", "İngiltere"],
    },
    reviews: [
      rv("Procurement, Hamburg", 5, "2026-04-11", "Teslimat terminlerine uyuyor. Dokümantasyon temiz."),
    ],
  },
  {
    slug: "anadolu-makine",
    name: "Anadolu Makine Sanayi",
    category: "b2b",
    subcategory: "Makine imalatı",
    city: "Bursa",
    citySlug: "bursa",
    district: "Nilüfer",
    country: "Türkiye",
    address: "NOSAB 15. Cadde No:22",
    lat: 40.2214,
    lng: 28.9412,
    phone: "+90 224 555 0022",
    rating: 4.3,
    reviewCount: 22,
    priceLevel: 3,
    tags: ["imalat", "otomotiv yan sanayi", "b2b"],
    amenities: ["ISO 9001", "IATF 16949"],
    description: "Otomotiv pres kalıpları. Ticari firma rehberi: sektör, tesis, çalışan bandı.",
    hours: officeHours(),
    cover: P.factory,
    photos: [P.factory, P.warehouse],
    verified: true,
    premium: false,
    quoteEnabled: true,
    intel: {
      founded: 2006,
      employees: "80–110",
      industry: "Makine / kalıp",
      revenue: "₺480M",
      exportMarkets: ["Polonya", "Çekya"],
    },
    reviews: [rv("OEM Satınalma", 4, "2026-01-30", "Numune süreci uzun ama kalite tutarlı.")],
  },
  {
    slug: "aegean-olive-export",
    name: "Aegean Olive Co.",
    category: "b2b",
    subcategory: "Zeytinyağı ihracatı",
    city: "İzmir",
    citySlug: "izmir",
    district: "Bornova",
    country: "Türkiye",
    address: "Kazımdirik Mah. 15",
    lat: 38.4621,
    lng: 27.2214,
    phone: "+90 232 555 0015",
    rating: 4.7,
    reviewCount: 17,
    priceLevel: 2,
    tags: ["zeytinyağı", "ihracat", "organik"],
    amenities: ["organik sertifika", "private label"],
    description: "Private label zeytinyağı. Çok ülkeli B2B dizinde İzmir kaydı.",
    hours: officeHours(),
    cover: P.warehouse,
    photos: [P.warehouse, P.office],
    verified: true,
    premium: true,
    intel: {
      founded: 2011,
      employees: "35–50",
      industry: "Gıda / zeytinyağı",
      exportMarkets: ["ABD", "Japonya", "İsveç"],
    },
    reviews: [rv("Buyer, Osaka", 5, "2026-02-02", "Acidity consistently under 0.4. Labels on time.")],
  },
  {
    slug: "pera-suite-hotel",
    name: "Pera Suite Hotel",
    category: "konaklama",
    subcategory: "Butik otel",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Beyoğlu",
    country: "Türkiye",
    address: "Meşrutiyet Caddesi 74, Tepebaşı",
    lat: 41.0328,
    lng: 28.9741,
    phone: "+90 212 555 0074",
    rating: 4.7,
    reviewCount: 2104,
    priceLevel: 3,
    tags: ["otel", "teras", "tarihi"],
    amenities: ["teras", "kahvaltı", "concierge", "wifi"],
    description: "Tripadvisor ruhu: güçlü yorum, fotoğraf ve mahalle skoru. Galata'ya yürüyüş mesafesi.",
    hours: everyday("00:00", "23:59"),
    cover: P.hotel,
    photos: [P.hotel, P.boutique, P.terrace],
    verified: true,
    premium: true,
    services: [{ id: "night", name: "Standart oda / gece", durationMin: 1440, price: 6200 }],
    reviews: [
      rv("Clara W.", 5, "2026-09-06", "Staff remembered our anniversary. Terrace breakfast is the highlight.", { visitType: "Çift" }),
      rv("Mert Ç.", 4, "2026-06-18", "Oda küçük ama konum yenilmez. Asansör yavaş."),
    ],
  },
  {
    slug: "kaleici-konak",
    name: "Kaleiçi Taş Konak",
    category: "konaklama",
    subcategory: "Pansiyon",
    city: "Antalya",
    citySlug: "antalya",
    district: "Muratpaşa",
    country: "Türkiye",
    address: "Hidırlık Sokak 8, Kaleiçi",
    lat: 36.8834,
    lng: 30.7052,
    phone: "+90 242 555 0008",
    rating: 4.8,
    reviewCount: 640,
    priceLevel: 2,
    tags: ["pansiyon", "tarihi", "kahvaltı"],
    amenities: ["kahvaltı", "bahçe", "klima"],
    description: "Restorasyonlu taş ev. Seyahat aramalarında 'otantik ve orta fiyat' filtresinde birinci.",
    hours: everyday("08:00", "22:00"),
    cover: P.boutique,
    photos: [P.boutique, P.garden],
    verified: true,
    premium: false,
    reviews: [rv("Jonas P.", 5, "2026-08-04", "Garden breakfast, thick walls, quiet nights.")],
  },
  {
    slug: "sisli-hukuk",
    name: "Kuzey Hukuk Bürosu",
    category: "profesyonel",
    subcategory: "Avukat",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Şişli",
    country: "Türkiye",
    address: "Halaskargazi 64",
    lat: 41.0541,
    lng: 28.9854,
    phone: "+90 212 555 0064",
    rating: 4.6,
    reviewCount: 88,
    priceLevel: 3,
    tags: ["hukuk", "ticaret", "teklif"],
    amenities: ["ön görüşme", "İngilizce"],
    description: "Ticaret ve iş hukuku. Angi gibi teklif: davayı anlatın, uygunluk ve ücret aralığı dönsün.",
    hours: officeHours(),
    cover: P.lawyer,
    photos: [P.lawyer, P.office],
    verified: true,
    premium: true,
    quoteEnabled: true,
    intel: { founded: 2014, employees: "8–12", industry: "Hukuk" },
    reviews: [rv("Start-up kurucu", 5, "2026-05-22", "Yatırım turu sözleşmelerinde net ve hızlı.")],
  },
  {
    slug: "ankara-mm",
    name: "Başkent Mali Müşavirlik",
    category: "profesyonel",
    subcategory: "Mali müşavir",
    city: "Ankara",
    citySlug: "ankara",
    district: "Çankaya",
    country: "Türkiye",
    address: "Kızılay, Atatürk Bulvarı 89",
    lat: 39.9188,
    lng: 32.8542,
    phone: "+90 312 555 0089",
    rating: 4.5,
    reviewCount: 61,
    priceLevel: 2,
    tags: ["muhasebe", "vergi", "teklif"],
    amenities: ["e-fatura", "şirket kuruluşu"],
    description: "Limited şirket kuruluşu ve e-fatura. Ücretsiz ön görüşme, sonra sabit paket.",
    hours: officeHours(),
    cover: P.account,
    photos: [P.account, P.office],
    verified: true,
    premium: false,
    quoteEnabled: true,
    intel: { founded: 2009, employees: "15–20", industry: "Muhasebe" },
    reviews: [rv("E-ticaret sahibi", 4, "2026-03-01", "KDV iadesinde süreç uzadı ama sonuç doğru.")],
  },
  {
    slug: "nisantasi-atelier",
    name: "Nişantaşı Atelier Mobilya",
    category: "alisveris",
    subcategory: "İç mimari & mobilya",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Şişli",
    country: "Türkiye",
    address: "Teşvikiye Caddesi 21",
    lat: 41.0512,
    lng: 28.9948,
    phone: "+90 212 555 0021",
    rating: 4.7,
    reviewCount: 143,
    priceLevel: 4,
    tags: ["mobilya", "dekor", "ölçü"],
    amenities: ["keşif", "3D çizim", "üretim"],
    description: "Houzz karışımı: görsel galeri, ürün ve uygulama ekibi. Mutfak çizimi teklifle başlar.",
    hours: officeHours(),
    cover: P.furniture,
    photos: [P.furniture, P.interior],
    verified: true,
    premium: true,
    quoteEnabled: true,
    reviews: [rv("Selin & Emre", 5, "2026-07-30", "Mutfak 3D'si gerçeğe çok yakındı. Teslim 1 hafta kaydı.")],
  },
  {
    slug: "london-showroom",
    name: "Hearth & Grain Showroom",
    category: "alisveris",
    subcategory: "Ev dekorasyonu",
    city: "Londra",
    citySlug: "london",
    district: "Hackney",
    country: "Birleşik Krallık",
    address: "Mare Street 140, Hackney",
    lat: 51.5456,
    lng: -0.0552,
    phone: "+44 20 5555 0140",
    rating: 4.6,
    reviewCount: 210,
    priceLevel: 3,
    tags: ["dekor", "seramik", "global"],
    amenities: ["showroom", "click & collect"],
    description: "Çok ülkeli dizin kaydı. Türkiye'den sipariş için ihracat masası var.",
    hours: officeHours(),
    cover: P.interior,
    photos: [P.interior, P.furniture],
    verified: true,
    premium: false,
    reviews: [rv("Priya L.", 5, "2026-06-11", "Glazes are unique. Staff knows the makers.")],
  },
  {
    slug: "kadikoy-oto",
    name: "Moda Oto Servis",
    category: "otomotiv",
    subcategory: "Yetkili olmayan servis",
    city: "İstanbul",
    citySlug: "istanbul",
    district: "Kadıköy",
    country: "Türkiye",
    address: "Rıhtım Caddesi 19",
    lat: 40.9928,
    lng: 29.0232,
    phone: "+90 216 555 0019",
    rating: 4.5,
    reviewCount: 480,
    priceLevel: 2,
    tags: ["yağ değişimi", "fren", "randevu"],
    amenities: ["randevu", "ikame yok", "orijinal yedek"],
    description: "Yağ, fren, klima. Randevusuz gelenler öğleden sonra alınır.",
    hours: officeHours(),
    cover: P.car,
    photos: [P.car, P.tools],
    verified: true,
    premium: false,
    services: [
      { id: "oil", name: "Yağ + filtre", durationMin: 60, price: 2800 },
      { id: "brake", name: "Fren balata kontrol", durationMin: 45, price: 900 },
    ],
    quoteEnabled: true,
    reviews: [
      rv("Yusuf C.", 5, "2026-09-10", "Yağ değişimi 50 dakikada, fiyat menüde yazılı."),
      rv("Dilek Ö.", 4, "2026-04-28", "Klima gazı biraz pahalı ama iş temiz."),
    ],
  },
  {
    slug: "nyc-brook-garage",
    name: "Brooklyn Hill Garage",
    category: "otomotiv",
    subcategory: "Oto servis",
    city: "New York",
    citySlug: "new-york",
    district: "Brooklyn",
    country: "ABD",
    address: "Atlantic Avenue 412",
    lat: 40.6769,
    lng: -73.9712,
    phone: "+1 718 555 0412",
    rating: 4.4,
    reviewCount: 890,
    priceLevel: 3,
    tags: ["inspection", "brake", "global"],
    amenities: ["appointment", "loaner"],
    description: "ABD kaydı: Yellow Pages + MapQuest tarzı lokal servis. Global dizinde örnek.",
    hours: officeHours(),
    cover: P.car,
    photos: [P.car],
    verified: true,
    premium: false,
    services: [{ id: "insp", name: "State inspection", durationMin: 40, price: 89 }],
    reviews: [rv("Marcus J.", 4, "2026-08-01", "Honest about a pad replacement I didn't need.")],
  },
]

export function getBusiness(slug: string) {
  return BUSINESSES.find((b) => b.slug === slug)
}

export function businessesByCategory(id: Business["category"]) {
  return BUSINESSES.filter((b) => b.category === id)
}

export function businessesByCity(slug: string) {
  return BUSINESSES.filter((b) => b.citySlug === slug)
}

export function featuredBusinesses() {
  return BUSINESSES.filter((b) => b.premium).slice(0, 6)
}

export function topReviewed() {
  return [...BUSINESSES].sort((a, b) => b.reviewCount - a.reviewCount).slice(0, 6)
}
