import { allSectors, seedSectors } from "@/lib/sectors"
import type {
  BookingKind,
  Business,
  CategoryId,
  DayHours,
  Review,
} from "@/lib/types"
import { zonguldakBusinesses } from "@/lib/zonguldak"

const DAYS = [
  "Pazartesi",
  "Salı",
  "Çarşamba",
  "Perşembe",
  "Cuma",
  "Cumartesi",
  "Pazar",
] as const

function hours(
  open: string,
  close: string,
  mode: "all" | "sun-off" | "weekend-off" = "sun-off",
): DayHours[] {
  return DAYS.map((day) => {
    const closed =
      (mode === "sun-off" && day === "Pazar") ||
      (mode === "weekend-off" && (day === "Cumartesi" || day === "Pazar"))
    return { day, hours: closed ? "Kapalı" : `${open}–${close}` }
  })
}

function reviews(items: [string, number, string, string][]): Review[] {
  return items.map(([author, rating, date, text], index) => ({
    id: `${author}-${date}-${index}`,
    author,
    rating,
    date,
    text,
    helpful: 3 + ((index * 5 + author.length) % 11),
  }))
}

type Draft = {
  slug: string
  name: string
  category: CategoryId
  subcategory: string
  city: string
  district: string
  address: string
  lat: number
  lng: number
  phone: string
  rating: number
  reviewCount: number
  priceLevel: 1 | 2 | 3 | 4
  openNow: boolean
  summary: string
  about: string
  services: Business["services"]
  amenities: string[]
  tags: string[]
  reviews: Review[]
  premium?: boolean
  verified?: boolean
  responseMinutes: number
  founded: number
  photo: string
  photoPosition?: string
  booking: BookingKind
  open: string
  close: string
  hoursMode?: "all" | "sun-off" | "weekend-off"
  facts?: Business["facts"]
}

function make(draft: Draft): Business {
  return {
    id: draft.slug,
    slug: draft.slug,
    name: draft.name,
    category: draft.category,
    subcategory: draft.subcategory,
    city: draft.city,
    district: draft.district,
    address: draft.address,
    lat: draft.lat,
    lng: draft.lng,
    phone: draft.phone,
    rating: draft.rating,
    reviewCount: draft.reviewCount,
    priceLevel: draft.priceLevel,
    openNow: draft.openNow,
    summary: draft.summary,
    about: draft.about,
    services: draft.services,
    amenities: draft.amenities,
    tags: draft.tags,
    reviews: draft.reviews,
    premium: draft.premium ?? false,
    verified: draft.verified ?? true,
    responseMinutes: draft.responseMinutes,
    founded: draft.founded,
    photo: draft.photo,
    photoPosition: draft.photoPosition ?? "center",
    booking: draft.booking,
    hours: hours(draft.open, draft.close, draft.hoursMode ?? "sun-off"),
    facts: draft.facts ?? [],
    source: "katalog",
  }
}

function sectorMake(
  draft: Pick<
    Draft,
    "slug" | "name" | "category" | "subcategory" | "city" | "district" | "lat" | "lng" | "summary" | "photo" | "booking"
  > &
    Partial<Draft>,
): Business {
  return make({
    address: `${draft.district}, ${draft.city}`,
    phone: "0212 555 40 00",
    rating: 4.5,
    reviewCount: 64,
    priceLevel: 2,
    openNow: true,
    about: `${draft.summary} Örnek sektör kaydıdır; randevu ve teklif bu tarayıcıda durur.`,
    services: [{ name: "Görüşme", price: 0, unit: "keşif" }],
    amenities: ["Randevu"],
    tags: [],
    reviews: reviews([["Mert Kaya", 5, "Eylül 2026", "Net konuştular, saat tuttu."]]),
    responseMinutes: 80,
    founded: 2014,
    open: "09:00",
    close: "18:00",
    ...draft,
  })
}

export const categories = seedSectors

export const cities = [
  { name: "İstanbul", lat: 41.015, lng: 28.979 },
  { name: "Ankara", lat: 39.92, lng: 32.854 },
  { name: "İzmir", lat: 38.423, lng: 27.143 },
  { name: "Antalya", lat: 36.896, lng: 30.713 },
  { name: "Bursa", lat: 40.195, lng: 29.061 },
  { name: "Zonguldak", lat: 41.453, lng: 31.789 },
]

export function cityCenter(name: string) {
  return cities.find((city) => city.name === name) ?? cities[0]
}

export const suggestions = [
  "Kadıköy'de çocukla gidilecek akşam yemeği",
  "Beşiktaş'ta bugün gelebilen boya ustası",
  "Nişantaşı diş temizliği, uygun fiyat",
  "Kaleiçi'nde deniz manzaralı butik otel",
  "Çankaya'da ofis temizliği",
  "Zonguldak'ta kebap",
  "Kadıköy'de oto servis",
  "Levent'te avukat",
  "Moda'da kreş",
]

const sampleBusinesses: Business[] = [
  make({
    slug: "balikci-mehmet",
    name: "Balıkçı Mehmet",
    category: "yeme",
    subcategory: "Balık restoranı",
    city: "İstanbul",
    district: "Karaköy",
    address: "Kemankeş Cad. No: 18, Karaköy",
    lat: 41.0234,
    lng: 28.9752,
    phone: "0212 555 01 18",
    rating: 4.7,
    reviewCount: 842,
    priceLevel: 4,
    openNow: true,
    summary: "Günün teknesinden balık, sakin servis ve Haliç’e bakan üst kat.",
    about:
      "Öğle ve akşam iki oturum çalışır. Rezervasyon olmadan gelenleri bara alır, masa için dönüş süresi kısadır. Çocuk menüsü yoktur; porsiyonlar paylaşılır.",
    services: [
      { name: "Günün balığı", price: 1450, unit: "porsiyon" },
      { name: "Meze tabağı", price: 680, unit: "kişi" },
      { name: "Üst kat masa", price: 0, unit: "rezervasyon" },
    ],
    amenities: ["Rezervasyon", "Deniz ürünü", "Üst kat", "Kart"],
    tags: ["aksam", "luks", "manzara"],
    reviews: reviews([
      ["Ece Yılmaz", 5, "Eylül 2026", "Levrek taze, yağ oranı yerindeydi. Üst kat gürültüsüz."],
      ["Kerem Acar", 4, "Ağustos 2026", "Hesap yüksek ama porsiyon dürüst. Cuma için iki gün önce yer ayırın."],
    ]),
    premium: true,
    responseMinutes: 35,
    founded: 1998,
    photo: "/photos/seafood.jpg",
    booking: "rezervasyon",
    open: "12:00",
    close: "23:30",
    hoursMode: "all",
  }),
  make({
    slug: "sofra-42",
    name: "Sofra 42",
    category: "yeme",
    subcategory: "Meyhane",
    city: "İstanbul",
    district: "Kadıköy",
    address: "Moda Cad. No: 42, Kadıköy",
    lat: 40.9846,
    lng: 29.0268,
    phone: "0216 555 01 42",
    rating: 4.6,
    reviewCount: 510,
    priceLevel: 2,
    openNow: true,
    summary: "Paylaşımlı meze, yüksek mama sandalyesi ve erken oturan ailelere ayrılmış ön salon.",
    about:
      "Akşam 17’den sonra aile masası için ön salonu açık tutar. Çocuklar için köfte ve ayran yazılıdır. Canlı müzik yalnızca cuma gecesi arka salondadır.",
    services: [
      { name: "Meze seçkisi", price: 420, unit: "kişi" },
      { name: "Izgara köfte", price: 390, unit: "porsiyon" },
      { name: "Aile masası", price: 0, unit: "rezervasyon" },
    ],
    amenities: ["Aile masası", "Mama sandalyesi", "Erken oturum", "Kart"],
    tags: ["aile", "aksam"],
    reviews: reviews([
      ["Selin Kara", 5, "Eylül 2026", "Çocukla 18:00’de gittik, ön salon sakindi. Meze taze ve hesap şaşırtmadı."],
      ["Mert Uslu", 4, "Temmuz 2026", "Cuma arka salon gürültülü. Hafta içi akşam daha rahat."],
    ]),
    responseMinutes: 50,
    founded: 2014,
    photo: "/photos/meyhane.jpg",
    booking: "rezervasyon",
    open: "12:00",
    close: "00:00",
    hoursMode: "all",
  }),
  make({
    slug: "marmara-kahvesi",
    name: "Marmara Kahvesi",
    category: "yeme",
    subcategory: "Kahvaltı & kafe",
    city: "İstanbul",
    district: "Cihangir",
    address: "Akarsu Yokuşu No: 9, Cihangir",
    lat: 41.0328,
    lng: 28.9834,
    phone: "0212 555 01 09",
    rating: 4.5,
    reviewCount: 388,
    priceLevel: 2,
    openNow: true,
    summary: "Serpme kahvaltı öğlene kadar, sonrasında filtre kahve ve iki kişilik çalışma masası.",
    about:
      "Laptop için prize yakın dört masa vardır. Kahvaltı 11:30’da biter. Yanında çocuklu gelenler için yüksek sandalye bulunur, oyun köşesi yoktur.",
    services: [
      { name: "Serpme kahvaltı", price: 540, unit: "kişi" },
      { name: "Filtre kahve", price: 145, unit: "fincan" },
      { name: "Çalışma masası", price: 0, unit: "saat" },
    ],
    amenities: ["Kahvaltı", "Priz", "Yüksek sandalye"],
    tags: ["kahvalti"],
    reviews: reviews([
      ["Deniz Aksoy", 5, "Ekim 2026", "Pazar 10:00 sırası kısaydı. Peynir tabağı geniş, çay demli geliyor."],
      ["Burcu Er", 4, "Haziran 2026", "Öğleden sonra sadece kahve. Çalışmak için uygun, kahvaltı için erken gidin."],
    ]),
    responseMinutes: 70,
    founded: 2018,
    photo: "/photos/cafe.jpg",
    booking: "rezervasyon",
    open: "08:30",
    close: "19:00",
    hoursMode: "all",
  }),
  make({
    slug: "nar-lokantasi",
    name: "Nar Lokantası",
    category: "yeme",
    subcategory: "Ev yemeği",
    city: "İstanbul",
    district: "Beşiktaş",
    address: "Barbaros Bulvarı No: 64, Beşiktaş",
    lat: 41.0452,
    lng: 29.0068,
    phone: "0212 555 01 64",
    rating: 4.3,
    reviewCount: 264,
    priceLevel: 1,
    openNow: true,
    summary: "Öğle tezgâhı: günlük üç ana yemek, pilav ve ayran. Akşam 19:00’da kapanır.",
    about:
      "Fiyatı mahalle lokantası seviyesinde tutar. Porsiyon büyüktür, masa örtüsü yoktur. Kart ve yemek kartı geçer.",
    services: [
      { name: "Günün yemeği", price: 240, unit: "porsiyon" },
      { name: "Çorba", price: 80, unit: "kase" },
      { name: "Paket", price: 20, unit: "kap" },
    ],
    amenities: ["Paket", "Yemek kartı", "Öğle servisi"],
    tags: ["ekonomik"],
    reviews: reviews([
      ["Hakan Demir", 4, "Eylül 2026", "Kuru fasulye ve pilav doyurucu. Öğle 12:30’da kuyruk olur, 13:30 sakin."],
      ["Ayşe Polat", 5, "Mayıs 2026", "Fiyat hâlâ mahalle lokantası. Türlü taze çıktı."],
    ]),
    responseMinutes: 120,
    founded: 2006,
    photo: "/photos/lokanta.jpg",
    booking: "rezervasyon",
    open: "11:00",
    close: "19:00",
  }),
  make({
    slug: "kuzey-izgara",
    name: "Kuzey Izgara",
    category: "yeme",
    subcategory: "Izgara",
    city: "İzmir",
    district: "Alsancak",
    address: "Kıbrıs Şehitleri Cad. No: 88, Alsancak",
    lat: 38.4368,
    lng: 27.1422,
    phone: "0232 555 01 88",
    rating: 4.4,
    reviewCount: 301,
    priceLevel: 2,
    openNow: true,
    summary: "Közde et ve mevsim salata. Akşam için kısa rezervasyon yeter.",
    about:
      "Bahçe yazın açıktır. Etler gramajla yazılır. Çocuk porsiyonu pirzola yarımı olarak gelir.",
    services: [
      { name: "Kuzu pirzola", price: 780, unit: "porsiyon" },
      { name: "Köfte", price: 420, unit: "porsiyon" },
      { name: "Bahçe masası", price: 0, unit: "rezervasyon" },
    ],
    amenities: ["Bahçe", "Gramaj", "Rezervasyon"],
    tags: ["aksam", "aile"],
    reviews: reviews([
      ["Cem Öz", 5, "Ağustos 2026", "Pirzola köz tadı net. Bahçe akşam serin, ceket alın."],
      ["Naz Aydın", 4, "Nisan 2026", "Salata büyük, et orta. Servis hızlıydı."],
    ]),
    responseMinutes: 40,
    founded: 2011,
    photo: "/photos/grill.jpg",
    booking: "rezervasyon",
    open: "12:00",
    close: "23:00",
    hoursMode: "all",
  }),
  make({
    slug: "cankaya-sofrasi",
    name: "Çankaya Sofrası",
    category: "yeme",
    subcategory: "Kahvaltı",
    city: "Ankara",
    district: "Çankaya",
    address: "Tunalı Hilmi Cad. No: 112, Çankaya",
    lat: 39.9042,
    lng: 32.8598,
    phone: "0312 555 01 12",
    rating: 4.4,
    reviewCount: 276,
    priceLevel: 2,
    openNow: true,
    summary: "Hafta sonu kahvaltısı 10:00’a kadar sıra yapar, hafta içi serpme sakin gider.",
    about:
      "Van kahvaltısı ve sade serpme ayrı fiyatlıdır. Üst kat daha sessizdir. Öğleden sonra yalnızca tatlı ve çay kalır.",
    services: [
      { name: "Serpme kahvaltı", price: 480, unit: "kişi" },
      { name: "Van kahvaltısı", price: 620, unit: "kişi" },
      { name: "Üst kat", price: 0, unit: "rezervasyon" },
    ],
    amenities: ["Kahvaltı", "Üst kat", "Tatlı"],
    tags: ["kahvalti"],
    reviews: reviews([
      ["Pınar Koç", 5, "Eylül 2026", "Hafta içi 09:30’da yer bulduk. Otlu peynir tazeydi."],
      ["Emre Şahin", 4, "Mart 2026", "Pazar kuyruğu 25 dakika. Rezervasyon yalnızca üst kata."],
    ]),
    responseMinutes: 55,
    founded: 2009,
    photo: "/photos/breakfast.jpg",
    booking: "rezervasyon",
    open: "08:00",
    close: "16:00",
    hoursMode: "all",
  }),
  make({
    slug: "kaleici-meyhane",
    name: "Kaleiçi Meyhane",
    category: "yeme",
    subcategory: "Meyhane",
    city: "Antalya",
    district: "Kaleiçi",
    address: "Hesapçı Sok. No: 21, Kaleiçi",
    lat: 36.8838,
    lng: 30.7056,
    phone: "0242 555 01 21",
    rating: 4.5,
    reviewCount: 640,
    priceLevel: 3,
    openNow: true,
    summary: "Limana bakan teras, akşam mezesi ve kısa canlı müzik.",
    about:
      "Teras rüzgârlıdır. Rezervasyonda ‘deniz tarafı’ diye not düşülürse ilk turda o masalar dolmadan haber verirler.",
    services: [
      { name: "Teras mezesi", price: 560, unit: "kişi" },
      { name: "Günün balığı", price: 980, unit: "porsiyon" },
      { name: "Deniz tarafı masa", price: 0, unit: "rezervasyon" },
    ],
    amenities: ["Teras", "Manzara", "Canlı müzik"],
    tags: ["aksam", "manzara"],
    reviews: reviews([
      ["Melis Tan", 5, "Temmuz 2026", "Gün batımında teras değer. Mezeler küçük tabak, iki kişiye üç meze yetti."],
      ["Okan Bilgin", 4, "Eylül 2026", "Müzik 21:30’da başlıyor. Daha sakin isterseniz erken oturun."],
    ]),
    responseMinutes: 45,
    founded: 2001,
    photo: "/photos/meyhane.jpg",
    photoPosition: "center top",
    booking: "rezervasyon",
    open: "13:00",
    close: "00:30",
    hoursMode: "all",
  }),
  make({
    slug: "kordon-kahve",
    name: "Kordon Kahve",
    category: "yeme",
    subcategory: "Kahvaltı & kafe",
    city: "İzmir",
    district: "Alsancak",
    address: "Kordon Boyu No: 14, Alsancak",
    lat: 38.4388,
    lng: 27.1404,
    phone: "0232 555 01 14",
    rating: 4.6,
    reviewCount: 455,
    priceLevel: 2,
    openNow: true,
    summary: "Kordon’a bakan kahvaltı ve öğlene kadar taze poğaça.",
    about:
      "Dışarı masa rüzgâr kesilince kapanır. İçeride priz vardır. Kahvaltı rezervasyonu hafta sonu için önerilir.",
    services: [
      { name: "Kordon kahvaltı", price: 510, unit: "kişi" },
      { name: "Poğaça tabağı", price: 180, unit: "tabak" },
      { name: "Filtre kahve", price: 130, unit: "fincan" },
    ],
    amenities: ["Manzara", "Kahvaltı", "Dışarı masa"],
    tags: ["kahvalti", "manzara"],
    reviews: reviews([
      ["Zeynep Uçar", 5, "Ağustos 2026", "Boyoz ve çay klasik. Dışarı masa için 09:00’dan önce gidin."],
      ["Baran Keskin", 4, "Şubat 2026", "Rüzgârlı günde içerisi daha iyi. Kahve dengeli."],
    ]),
    responseMinutes: 60,
    founded: 2016,
    photo: "/photos/cafe.jpg",
    photoPosition: "center top",
    booking: "rezervasyon",
    open: "08:00",
    close: "20:00",
    hoursMode: "all",
  }),
  make({
    slug: "han-firini",
    name: "Han Fırını",
    category: "yeme",
    subcategory: "Fırın & kahve",
    city: "Bursa",
    district: "Nilüfer",
    address: "Özlüce Cad. No: 7, Nilüfer",
    lat: 40.2144,
    lng: 28.9512,
    phone: "0224 555 01 07",
    rating: 4.2,
    reviewCount: 129,
    priceLevel: 1,
    openNow: false,
    summary: "Sabah pideleri ve öğlene kadar simit. Akşam kapalı.",
    about:
      "Üretim erken biter. 14:00’ten sonra yalnızca paketli ürün kalır. Doğrulama belgesi henüz tamamlanmamıştır.",
    services: [
      { name: "Simit", price: 25, unit: "adet" },
      { name: "Peynirli pide", price: 90, unit: "adet" },
      { name: "Filtre kahve", price: 80, unit: "fincan" },
    ],
    amenities: ["Paket", "Sabah üretimi"],
    tags: ["ekonomik", "kahvalti"],
    reviews: reviews([
      ["Tolga Şen", 4, "Eylül 2026", "Pide hamuru ince ve sıcak çıktı. 13:00’te çeşit azalıyor."],
      ["Aslı Erdem", 4, "Ocak 2026", "Simit gevrek. Oturma alanı küçük, çoğunluk paket."],
    ]),
    verified: false,
    responseMinutes: 180,
    founded: 2021,
    photo: "/photos/bakery.jpg",
    booking: "rezervasyon",
    open: "07:00",
    close: "15:00",
  }),
  make({
    slug: "pera-han",
    name: "Pera Han",
    category: "konaklama",
    subcategory: "Butik otel",
    city: "İstanbul",
    district: "Beyoğlu",
    address: "Meşrutiyet Cad. No: 51, Beyoğlu",
    lat: 41.0348,
    lng: 28.9776,
    phone: "0212 555 02 51",
    rating: 4.8,
    reviewCount: 920,
    priceLevel: 4,
    openNow: true,
    summary: "On sekiz odalı butik otel, kahvaltı terası ve geç çıkış hafta içi mümkün.",
    about:
      "Odalar küçüktür, yataklar yenidir. Sokak gürültüsü için iç avlu odası isteyin. Kahvaltı 10:30’a kadar.",
    services: [
      { name: "Avlu odası", price: 7400, unit: "gece" },
      { name: "Teras odası", price: 9800, unit: "gece" },
      { name: "Geç çıkış", price: 900, unit: "öğle" },
    ],
    amenities: ["Kahvaltı", "Geç çıkış", "İç avlu"],
    tags: ["butik", "luks"],
    reviews: reviews([
      ["Elif Sönmez", 5, "Eylül 2026", "Avlu odası sessizdi. Kahvaltıda peynir çeşidi iyi, oda gerçekten küçük."],
      ["Can Ersoy", 5, "Haziran 2026", "Konum yürünebilir. Resepsiyon geç çıkışı nazikçe ayarladı."],
    ]),
    premium: true,
    responseMinutes: 25,
    founded: 2012,
    photo: "/photos/boutique.jpg",
    booking: "rezervasyon",
    open: "00:00",
    close: "23:59",
    hoursMode: "all",
  }),
  make({
    slug: "lara-sahil",
    name: "Lara Sahil Suit",
    category: "konaklama",
    subcategory: "Sahil suit",
    city: "Antalya",
    district: "Lara",
    address: "Lara Cad. No: 220, Lara",
    lat: 36.8564,
    lng: 30.7528,
    phone: "0242 555 02 20",
    rating: 4.6,
    reviewCount: 704,
    priceLevel: 3,
    openNow: true,
    summary: "Denize yürüyüş mesafesinde suit, kahvaltı sepette odaya gelir.",
    about:
      "Havuz küçüktür, deniz önceliklidir. Yazın minimum üç gece ister. Kışın tek gece açıktır.",
    services: [
      { name: "Deniz suit", price: 8600, unit: "gece" },
      { name: "Aile suit", price: 11200, unit: "gece" },
      { name: "Sepet kahvaltı", price: 0, unit: "dahil" },
    ],
    amenities: ["Deniz", "Kahvaltı", "Aile odası"],
    tags: ["manzara", "luks", "aile"],
    reviews: reviews([
      ["Burcu Alem", 5, "Ağustos 2026", "Sahile iniş iki dakika. Suit mutfaklı, çocukla üç gece rahat."],
      ["Emre Kılıç", 4, "Ekim 2025", "Havuz küçük, biz denizi kullandık. Kahvaltı yeterince taze."],
    ]),
    premium: true,
    responseMinutes: 30,
    founded: 2015,
    photo: "/photos/suite.jpg",
    booking: "rezervasyon",
    open: "00:00",
    close: "23:59",
    hoursMode: "all",
  }),
  make({
    slug: "han-konagi",
    name: "Han Konağı",
    category: "konaklama",
    subcategory: "Butik konak",
    city: "Antalya",
    district: "Kaleiçi",
    address: "Kılıçarslan Sok. No: 6, Kaleiçi",
    lat: 36.8846,
    lng: 30.7064,
    phone: "0242 555 02 06",
    rating: 4.7,
    reviewCount: 488,
    priceLevel: 3,
    openNow: true,
    summary: "Taş konakta sekiz oda, liman tarafı balkon ve sade kahvaltı.",
    about:
      "Merdivenler dardır, bavul için yardım ister. Liman manzaralı iki oda vardır, rezervasyonda not düşün.",
    services: [
      { name: "Avlu odası", price: 5200, unit: "gece" },
      { name: "Liman odası", price: 6900, unit: "gece" },
      { name: "Kahvaltı", price: 0, unit: "dahil" },
    ],
    amenities: ["Butik", "Manzara", "Kahvaltı"],
    tags: ["butik", "manzara"],
    reviews: reviews([
      ["Deniz Oral", 5, "Eylül 2026", "Liman odasının balkonundan gün batımı net görünüyor. Merdiven dik."],
      ["Selin Ak", 4, "Mayıs 2026", "Kahvaltı sade ve temiz. Sokak akşam hareketli, avlu oda daha sessiz."],
    ]),
    responseMinutes: 40,
    founded: 2008,
    photo: "/photos/konak.jpg",
    booking: "rezervasyon",
    open: "00:00",
    close: "23:59",
    hoursMode: "all",
  }),
  make({
    slug: "bebek-konak",
    name: "Bebek Konak",
    category: "konaklama",
    subcategory: "Sahil otel",
    city: "İstanbul",
    district: "Bebek",
    address: "Cevdet Paşa Cad. No: 33, Bebek",
    lat: 41.0772,
    lng: 29.0436,
    phone: "0212 555 02 33",
    rating: 4.7,
    reviewCount: 356,
    priceLevel: 4,
    openNow: true,
    summary: "Boğaz’a bakan kahvaltı salonu ve az odalı konaklama.",
    about:
      "Otopark anlaşmalıdır, vale vardır. Odalar yenilenmiştir. Çocuk yaş sınırı yoktur.",
    services: [
      { name: "Boğaz odası", price: 12400, unit: "gece" },
      { name: "Bahçe odası", price: 9800, unit: "gece" },
      { name: "Vale", price: 400, unit: "gece" },
    ],
    amenities: ["Manzara", "Vale", "Kahvaltı"],
    tags: ["luks", "manzara"],
    reviews: reviews([
      ["Aslı Kurt", 5, "Temmuz 2026", "Kahvaltı salonu manzarası asıl olay. Oda sessiz, yatak sertçe."],
      ["Kerem Tan", 4, "Nisan 2026", "Vale iş gördü. Fiyat yüksek, konum buna göre."],
    ]),
    responseMinutes: 35,
    founded: 2004,
    photo: "/photos/hotel.jpg",
    booking: "rezervasyon",
    open: "00:00",
    close: "23:59",
    hoursMode: "all",
  }),
  make({
    slug: "atolye-sac",
    name: "Atölye Saç",
    category: "guzellik",
    subcategory: "Kuaför",
    city: "İstanbul",
    district: "Nişantaşı",
    address: "Teşvikiye Cad. No: 27, Nişantaşı",
    lat: 41.0516,
    lng: 28.9948,
    phone: "0212 555 03 27",
    rating: 4.8,
    reviewCount: 612,
    priceLevel: 3,
    openNow: true,
    summary: "Kesim ve renk için süre yazılı randevu. Danışmasız koltuk yok.",
    about:
      "İlk gelişte on beş dakikalık saç analizi zorunludur. Geç kalınan randevu kısaltılır, iptal dört saat önceden ücretsizdir.",
    services: [
      { name: "Kadın kesim", price: 2200, unit: "seans" },
      { name: "Erkek kesim", price: 1400, unit: "seans" },
      { name: "Boya", price: 4800, unit: "seans" },
    ],
    amenities: ["Randevu", "Saç analizi", "İptal politikası"],
    tags: [],
    reviews: reviews([
      ["Ece Nur", 5, "Eylül 2026", "Kesim tam istediğim uzunlukta. Analiz kısa sürdü, acele hissettirmediler."],
      ["Melis Akın", 4, "Haziran 2026", "Boya fiyatı yüksek, kalıcılığı üç hafta sonra hâlâ iyiydi."],
    ]),
    premium: true,
    responseMinutes: 20,
    founded: 2017,
    photo: "/photos/salon.jpg",
    booking: "randevu",
    open: "10:00",
    close: "20:00",
  }),
  make({
    slug: "mudita-spa",
    name: "Mudita Spa",
    category: "guzellik",
    subcategory: "Spa",
    city: "İstanbul",
    district: "Kadıköy",
    address: "Caferağa Mah. Moda Cad. No: 118, Kadıköy",
    lat: 40.9862,
    lng: 29.0254,
    phone: "0216 555 03 18",
    rating: 4.6,
    reviewCount: 240,
    priceLevel: 3,
    openNow: true,
    summary: "Tek kişilik oda, aromaterapi ve 50 ya da 80 dakikalık masaj.",
    about:
      "Çift oda yoktur. Geç kalan seansı kısaltır. Hamilelikte ikinci üç aydan itibaren doktor notu ister.",
    services: [
      { name: "Sırt masajı", price: 1800, unit: "50 dk" },
      { name: "Tüm vücut", price: 2600, unit: "80 dk" },
      { name: "Aromaterapi", price: 400, unit: "ek" },
    ],
    amenities: ["Tek oda", "Duş", "Randevu"],
    tags: [],
    reviews: reviews([
      ["Nazlı Demir", 5, "Ağustos 2026", "Oda sessiz, baskı ayarını sordular. 80 dakika yetti."],
      ["Ece Bal", 4, "Mart 2026", "Randevu saatinde aldılar. Duş suyu biraz ılık kaldı."],
    ]),
    responseMinutes: 30,
    founded: 2019,
    photo: "/photos/spa.jpg",
    booking: "randevu",
    open: "11:00",
    close: "21:00",
    hoursMode: "all",
  }),
  make({
    slug: "kilcik-berber",
    name: "Kılçık Berber",
    category: "guzellik",
    subcategory: "Berber",
    city: "İstanbul",
    district: "Karaköy",
    address: "Necatibey Cad. No: 40, Karaköy",
    lat: 41.0246,
    lng: 28.9768,
    phone: "0212 555 03 40",
    rating: 4.4,
    reviewCount: 198,
    priceLevel: 1,
    openNow: true,
    summary: "Sıra usulü erkek kesimi ve sakal. Randevu yalnızca öğleden sonra.",
    about:
      "Sabah sıra yürür, öğleden sonra iki berber randevulu çalışır. Fiyat mahalle berberi seviyesindedir.",
    services: [
      { name: "Saç kesimi", price: 450, unit: "seans" },
      { name: "Sakal", price: 250, unit: "seans" },
      { name: "Kesim + sakal", price: 600, unit: "seans" },
    ],
    amenities: ["Sıra", "Randevu", "Nakit ve kart"],
    tags: ["ekonomik"],
    reviews: reviews([
      ["Okan Yurt", 5, "Eylül 2026", "15 dakikada çıktım. Ense temiz, fiyat dürüst."],
      ["Cem Ak", 4, "Ocak 2026", "Öğle sırası uzundu. Randevu daha rahat."],
    ]),
    responseMinutes: 25,
    founded: 2013,
    photo: "/photos/barber.jpg",
    booking: "randevu",
    open: "09:00",
    close: "20:00",
  }),
  make({
    slug: "luma-cilt",
    name: "Luma Cilt",
    category: "guzellik",
    subcategory: "Cilt bakımı",
    city: "Ankara",
    district: "Çankaya",
    address: "Kızılırmak Mah. No: 8, Çankaya",
    lat: 39.9018,
    lng: 32.8124,
    phone: "0312 555 03 08",
    rating: 4.5,
    reviewCount: 166,
    priceLevel: 3,
    openNow: false,
    summary: "Cilt analizi sonrası protokol. Aynı gün randevu seyrektir.",
    about:
      "İlk seans analizle birlikte 70 dakika sürer. Leke protokolü üç seans paketidir. Pazar kapalıdır.",
    services: [
      { name: "Cilt analizi", price: 900, unit: "seans" },
      { name: "Hydrafacial", price: 3200, unit: "seans" },
      { name: "Leke paketi", price: 8400, unit: "3 seans" },
    ],
    amenities: ["Analiz", "Paket", "Randevu"],
    tags: [],
    reviews: reviews([
      ["Pınar El", 5, "Temmuz 2026", "Analiz aceleye gelmedi. Ürün satışı baskılı değildi."],
      ["Selin Öz", 4, "Şubat 2026", "Hydrafacial sonrası kızarıklık bir gün sürdü, önceden söylediler."],
    ]),
    responseMinutes: 80,
    founded: 2020,
    photo: "/photos/skin.jpg",
    booking: "randevu",
    open: "10:00",
    close: "19:00",
  }),
  make({
    slug: "kumsal-boya",
    name: "Kumsal Boya",
    category: "ev",
    subcategory: "Boya ustası",
    city: "İstanbul",
    district: "Beşiktaş",
    address: "Vişnezade Mah. No: 15, Beşiktaş",
    lat: 41.0438,
    lng: 29.0022,
    phone: "0532 555 04 15",
    rating: 4.7,
    reviewCount: 214,
    priceLevel: 2,
    openNow: true,
    summary: "İç cephe boya. Keşif aynı gün, işe çoğu zaman ertesi sabah başlar.",
    about:
      "Boya markasını siz seçebilir ya da onların stok ettiği iki markadan gidebilirsiniz. Mobilya örtme dahildir, eşya taşıma ayrıca yazılır.",
    services: [
      { name: "Oda boyası", price: 7500, unit: "oda" },
      { name: "2+1 daire", price: 28000, unit: "iş" },
      { name: "Keşif", price: 0, unit: "aynı gün" },
    ],
    amenities: ["Aynı gün keşif", "Örtme dahil", "Yazılı metraj"],
    tags: ["acil"],
    reviews: reviews([
      ["Mert Avcı", 5, "Eylül 2026", "Salı aradım, akşam keşif geldi, perşembe bitti. Köşeler temiz."],
      ["Elif Tan", 4, "Mayıs 2026", "Fiyat keşifte netleşti, sürpriz çıkmadı. Bir priz kapağını unutmuşlar, aynı gün taktılar."],
    ]),
    premium: true,
    responseMinutes: 20,
    founded: 2010,
    photo: "/photos/paint.jpg",
    booking: "teklif",
    open: "08:30",
    close: "19:00",
    hoursMode: "all",
  }),
  make({
    slug: "beyaz-ev-temizlik",
    name: "Beyaz Ev Temizlik",
    category: "temizlik",
    subcategory: "Ev temizliği",
    city: "İstanbul",
    district: "Kadıköy",
    address: "Caferağa Mah. No: 3, Kadıköy",
    lat: 40.9904,
    lng: 29.0288,
    phone: "0533 555 04 03",
    rating: 4.5,
    reviewCount: 340,
    priceLevel: 2,
    openNow: true,
    summary: "Saatlik ve daire bazlı temizlik. Malzeme sizden ya da ekipten.",
    about:
      "İki kişilik ekip 2+1 daireyi yaklaşık dört saatte çıkarır. Düzenli müşteriye sabit gün verilir.",
    services: [
      { name: "2+1 genel", price: 3200, unit: "ziyaret" },
      { name: "Saatlik", price: 750, unit: "saat" },
      { name: "Malzeme", price: 350, unit: "ziyaret" },
    ],
    amenities: ["Malzeme seçeneği", "Sabit gün", "İki kişilik ekip"],
    tags: ["ekonomik"],
    reviews: reviews([
      ["Ayşe Lale", 5, "Eylül 2026", "Fırın içi ve pervazlar dahil edildi. Saat tuttu."],
      ["Deniz Ulu", 4, "Nisan 2026", "İlk seferde banyo derzi eksik kalmıştı, ücretsiz tamamladılar."],
    ]),
    responseMinutes: 35,
    founded: 2016,
    photo: "/photos/cleaning.jpg",
    booking: "teklif",
    open: "08:00",
    close: "18:30",
  }),
  make({
    slug: "baskent-ofis-temizlik",
    name: "Başkent Ofis Temizlik",
    category: "temizlik",
    subcategory: "Ofis temizliği",
    city: "Ankara",
    district: "Çankaya",
    address: "Çankaya Cad. No: 90, Çankaya",
    lat: 39.9002,
    lng: 32.8634,
    phone: "0312 555 04 90",
    rating: 4.4,
    reviewCount: 188,
    priceLevel: 2,
    openNow: true,
    summary: "Mesai sonrası ofis temizliği. Sözleşme aylık ya da tek sefer.",
    about:
      "Akşam 18:30’dan sonra girerler. Kartlı geçiş için bir kişi refakat ister. Teklif metrekareye göredir.",
    services: [
      { name: "100 m² ofis", price: 4500, unit: "ziyaret" },
      { name: "Aylık 8 ziyaret", price: 28000, unit: "ay" },
      { name: "Cam", price: 1200, unit: "sefer" },
    ],
    amenities: ["Mesai sonrası", "Sözleşme", "Cam"],
    tags: ["ofis"],
    reviews: reviews([
      ["Emre Bal", 5, "Ağustos 2026", "Toplantı odası camları dahil. Gece girişi sorunsuz."],
      ["Hakan Er", 4, "Ocak 2026", "İlk hafta çöp saati kaydı, sonra düzelttiler."],
    ]),
    responseMinutes: 40,
    founded: 2012,
    photo: "/photos/cleaning.jpg",
    photoPosition: "center top",
    booking: "teklif",
    open: "09:00",
    close: "18:30",
  }),
  make({
    slug: "alsancak-mutfak",
    name: "Alsancak Mutfak",
    category: "ev",
    subcategory: "Mutfak dolabı",
    city: "İzmir",
    district: "Alsancak",
    address: "Kıbrıs Şehitleri Cad. No: 140, Alsancak",
    lat: 38.4342,
    lng: 27.1448,
    phone: "0232 555 04 40",
    rating: 4.6,
    reviewCount: 152,
    priceLevel: 3,
    openNow: true,
    summary: "Ölçü alıp mutfak dolabı üretir. Numune atölyede görülür.",
    about:
      "Teslim çoğu işte dört ile altı haftadır. Tezgâh taşı ayrıca fiyatlanır. Çizim revizyonu iki tura kadar ücretsizdir.",
    services: [
      { name: "Keşif ve çizim", price: 0, unit: "ilk" },
      { name: "Düz mutfak", price: 185000, unit: "iş" },
      { name: "Ada mutfak", price: 260000, unit: "iş" },
    ],
    amenities: ["Çizim", "Atölye", "Ölçü"],
    tags: [],
    reviews: reviews([
      ["Zeynep Mor", 5, "Haziran 2026", "Çizim iki turda oturdu. Montaj üç gün sürdü, süpürgelik hizası düzgün."],
      ["Caner Ak", 4, "Kasım 2025", "Süre altı haftayı biraz aştı, haber verdiler. Malzeme söz verilen gibiydi."],
    ]),
    responseMinutes: 180,
    founded: 2007,
    photo: "/photos/kitchen.jpg",
    booking: "teklif",
    open: "09:30",
    close: "18:30",
  }),
  make({
    slug: "cankaya-boya",
    name: "Çankaya Boya",
    category: "ev",
    subcategory: "Boya ustası",
    city: "Ankara",
    district: "Çankaya",
    address: "Bahçelievler Mah. No: 22, Çankaya",
    lat: 39.9254,
    lng: 32.8266,
    phone: "0312 555 04 22",
    rating: 4.3,
    reviewCount: 141,
    priceLevel: 2,
    openNow: true,
    summary: "İç cephe ve tavan. Keşif iki gün içinde.",
    about:
      "Aynı gün çıkış vermez, planlı iş alır. Nemli duvarda astar ayrıca yazılır.",
    services: [
      { name: "Oda boyası", price: 6800, unit: "oda" },
      { name: "Tavan", price: 2200, unit: "oda" },
      { name: "Keşif", price: 0, unit: "iki gün" },
    ],
    amenities: ["Yazılı teklif", "Astar notu"],
    tags: [],
    reviews: reviews([
      ["Tolga Bin", 4, "Temmuz 2026", "İş temiz bitti. Aynı gün gelemediler, tarihi baştan söylediler."],
      ["Aslı Pek", 4, "Mart 2026", "Renk kartelasını evde bıraktılar, karar vermek kolay oldu."],
    ]),
    responseMinutes: 240,
    founded: 2011,
    photo: "/photos/paint.jpg",
    photoPosition: "left center",
    booking: "teklif",
    open: "08:30",
    close: "18:00",
  }),
  make({
    slug: "hizli-tesisat",
    name: "Hızlı Tesisat",
    category: "usta",
    subcategory: "Tesisatçı",
    city: "İstanbul",
    district: "Şişli",
    address: "Halaskargazi Cad. No: 76, Şişli",
    lat: 41.0602,
    lng: 28.9874,
    phone: "0532 555 05 76",
    rating: 4.5,
    reviewCount: 428,
    priceLevel: 2,
    openNow: true,
    summary: "Su kaçağı ve tıkanıklık için aynı gün çıkış. İş öncesi fiyat aralığı söylenir.",
    about:
      "Kamera tespit ayrıca ücretlidir ve onayınız olmadan başlanmaz. Gece tarifesi 22:00’den sonra uygulanır.",
    services: [
      { name: "Keşif çıkışı", price: 1500, unit: "ziyaret" },
      { name: "Musluk değişimi", price: 2200, unit: "iş" },
      { name: "Gider açma", price: 2800, unit: "nokta" },
    ],
    amenities: ["Aynı gün", "Kamera", "Yazılı aralık"],
    tags: ["acil"],
    reviews: reviews([
      ["Kerem Su", 5, "Eylül 2026", "Öğlen aradım, 16:00’da geldi. Gideri açtı, fiyat başta söylenenin içinde kaldı."],
      ["Nazan Ak", 4, "Şubat 2026", "Gece tarifesi yüksekti ama söylendi. İş bitti."],
    ]),
    responseMinutes: 15,
    founded: 2009,
    photo: "/photos/plumber.jpg",
    booking: "teklif",
    open: "08:00",
    close: "22:00",
    hoursMode: "all",
  }),
  make({
    slug: "volt-elektrik",
    name: "Volt Elektrik",
    category: "usta",
    subcategory: "Elektrikçi",
    city: "İstanbul",
    district: "Üsküdar",
    address: "Ahmediye Cad. No: 11, Üsküdar",
    lat: 41.0258,
    lng: 29.0156,
    phone: "0535 555 05 11",
    rating: 4.6,
    reviewCount: 263,
    priceLevel: 2,
    openNow: true,
    summary: "Pano, priz ve aydınlatma. Küçük iş aynı gün, pano için randevu.",
    about:
      "Sigorta ve kaçak akım rolesi stoğu araçtadır. Proje gerektiren işleri üstlenmez, daire içi iş alır.",
    services: [
      { name: "Servis çıkışı", price: 1200, unit: "ziyaret" },
      { name: "Priz hattı", price: 1800, unit: "nokta" },
      { name: "Avize montajı", price: 900, unit: "adet" },
    ],
    amenities: ["Araç stoğu", "Aynı gün küçük iş"],
    tags: ["acil"],
    reviews: reviews([
      ["Caner Yıl", 5, "Ağustos 2026", "Kaçak rolesini değiştirdi, testi gösterdi. Fatura bıraktı."],
      ["Ece Mut", 4, "Aralık 2025", "Avize montajı hızlıydı. Randevu saatine 20 dakika geç geldi, haber verdi."],
    ]),
    responseMinutes: 30,
    founded: 2014,
    photo: "/photos/electric.jpg",
    booking: "teklif",
    open: "09:00",
    close: "19:30",
    hoursMode: "all",
  }),
  make({
    slug: "kapi-tamirhane",
    name: "Kapı Tamirhane",
    category: "usta",
    subcategory: "Kapı ve kilit",
    city: "Bursa",
    district: "Nilüfer",
    address: "Ataevler Mah. No: 19, Nilüfer",
    lat: 40.2088,
    lng: 28.9624,
    phone: "0224 555 05 19",
    rating: 4.1,
    reviewCount: 96,
    priceLevel: 2,
    openNow: false,
    summary: "Amerikan kapı, kilit ve menteşe. Randevu ile gelir.",
    about:
      "Acil gece hizmeti yoktur. Kilit değişiminde eski kilidi size bırakır. Doğrulama sürecindedir.",
    services: [
      { name: "Kilit değişimi", price: 1600, unit: "adet" },
      { name: "Menteşe", price: 700, unit: "kapı" },
      { name: "Kapı ayarı", price: 900, unit: "kapı" },
    ],
    amenities: ["Randevulu", "Parça faturası"],
    tags: [],
    reviews: reviews([
      ["Hakan Nil", 4, "Haziran 2026", "Kapı sürtmesi geçti. Randevu ertesi gündü."],
      ["Melis Bur", 4, "Ekim 2025", "Kilit markasını seçmeme izin verdiler."],
    ]),
    verified: false,
    responseMinutes: 300,
    founded: 2018,
    photo: "/photos/repair.jpg",
    booking: "teklif",
    open: "09:00",
    close: "18:00",
  }),
  make({
    slug: "klima-24",
    name: "Klima 24",
    category: "usta",
    subcategory: "Klima servisi",
    city: "Antalya",
    district: "Lara",
    address: "Lara Yolu No: 48, Lara",
    lat: 36.8588,
    lng: 30.7482,
    phone: "0242 555 05 48",
    rating: 4.4,
    reviewCount: 275,
    priceLevel: 2,
    openNow: true,
    summary: "Bakım, gaz ve montaj. Yazın aynı gün bakım için sabah aramak gerekir.",
    about:
      "Gaz basmadan önce kaçak kontrolü yapılır. Montaj keşfi ayrıca yer göstermenizi ister.",
    services: [
      { name: "Bakım", price: 1400, unit: "iç ünite" },
      { name: "Gaz", price: 2200, unit: "iş" },
      { name: "Montaj", price: 3500, unit: "ünite" },
    ],
    amenities: ["Kaçak kontrolü", "Aynı gün bakım"],
    tags: ["acil"],
    reviews: reviews([
      ["Okan Lara", 5, "Temmuz 2026", "Sabah 08:30’da aradım, öğlen bakım yapıldı. Filtreyi gösterdiler."],
      ["Deniz Su", 4, "Ağustos 2025", "Gaz işi kaçak yüzünden uzadı, ücreti baştan güncellediler."],
    ]),
    responseMinutes: 25,
    founded: 2013,
    photo: "/photos/ac.jpg",
    booking: "teklif",
    open: "08:00",
    close: "20:00",
    hoursMode: "all",
  }),
  make({
    slug: "nisanta-dent",
    name: "Nişanta Dent",
    category: "saglik",
    subcategory: "Diş kliniği",
    city: "İstanbul",
    district: "Nişantaşı",
    address: "Valikonağı Cad. No: 19, Nişantaşı",
    lat: 41.0528,
    lng: 28.9962,
    phone: "0212 555 06 19",
    rating: 4.6,
    reviewCount: 530,
    priceLevel: 2,
    openNow: true,
    summary: "Diş taşı temizliği ve kontrol. İlk randevu çoğu gün boşluk bulur.",
    about:
      "Temizlik 40 dakikadır. Röntgen gerekirse aynı ziyarette çekilir ve ayrıca ücretlenir. Hafta sonu yalnızca cumartesi sabah açıktır.",
    services: [
      { name: "Diş taşı temizliği", price: 2800, unit: "seans" },
      { name: "Kontrol", price: 800, unit: "ziyaret" },
      { name: "Röntgen", price: 600, unit: "çekim" },
    ],
    amenities: ["Randevu", "Aynı gün röntgen", "Cumartesi sabah"],
    tags: ["ekonomik"],
    reviews: reviews([
      ["Selin Diş", 5, "Eylül 2026", "Temizlik nazikti, süre uzamadı. Fiyat sitedekiyle aynı çıktı."],
      ["Mert Kol", 4, "Mayıs 2026", "Cumartesi 09:00 randevusu dakikti. Bekleme alanı sakin."],
    ]),
    premium: true,
    responseMinutes: 20,
    founded: 2011,
    photo: "/photos/dental.jpg",
    booking: "randevu",
    open: "09:00",
    close: "19:00",
  }),
  make({
    slug: "kadikoy-fizik",
    name: "Kadıköy Fizik",
    category: "saglik",
    subcategory: "Fizyoterapi",
    city: "İstanbul",
    district: "Kadıköy",
    address: "Bahariye Cad. No: 55, Kadıköy",
    lat: 40.9918,
    lng: 29.0272,
    phone: "0216 555 06 55",
    rating: 4.7,
    reviewCount: 214,
    priceLevel: 2,
    openNow: true,
    summary: "Tek terapistle seans. Bel ve diz için değerlendirme ilk gelişte ücretsizdir.",
    about:
      "Seans 45 dakikadır. Paket sekiz seanstır, kullanılmayan seans 60 gün içinde devredilir.",
    services: [
      { name: "Değerlendirme", price: 0, unit: "ilk" },
      { name: "Tek seans", price: 1600, unit: "45 dk" },
      { name: "8 seans", price: 11200, unit: "paket" },
    ],
    amenities: ["Tek terapist", "Paket", "Değerlendirme"],
    tags: [],
    reviews: reviews([
      ["Ayşe Diz", 5, "Ağustos 2026", "Aynı terapistle devam ettim, bu fark etti. Egzersizi yazılı verdiler."],
      ["Emre Bel", 4, "Ocak 2026", "Akşam seansı dolu oluyor. Öğlen daha rahat."],
    ]),
    responseMinutes: 45,
    founded: 2015,
    photo: "/photos/physio.jpg",
    booking: "randevu",
    open: "09:00",
    close: "20:00",
  }),
  make({
    slug: "alsancak-goz",
    name: "Alsancak Göz",
    category: "saglik",
    subcategory: "Göz kliniği",
    city: "İzmir",
    district: "Alsancak",
    address: "Şair Eşref Bulvarı No: 30, Alsancak",
    lat: 38.4326,
    lng: 27.1436,
    phone: "0232 555 06 30",
    rating: 4.5,
    reviewCount: 188,
    priceLevel: 3,
    openNow: true,
    summary: "Gözlük muayenesi ve kontrol. Lens denemesi randevuya dahildir.",
    about:
      "Damla sonrası 20 dakika beklenir. Araçla gelene refakat önerilir. Çocuk muayenesi ayrıca saattedir.",
    services: [
      { name: "Muayene", price: 1800, unit: "ziyaret" },
      { name: "Lens deneme", price: 0, unit: "dahil" },
      { name: "Çocuk muayene", price: 1600, unit: "ziyaret" },
    ],
    amenities: ["Lens deneme", "Çocuk saati"],
    tags: ["aile"],
    reviews: reviews([
      ["Zeynep Göz", 5, "Eylül 2026", "Damla sonrası bekleme söylendiği gibiydi. Reçete net yazıldı."],
      ["Baran İnce", 4, "Nisan 2026", "Lens denemesi acele ettirilmedi."],
    ]),
    responseMinutes: 50,
    founded: 2008,
    photo: "/photos/clinic.jpg",
    booking: "randevu",
    open: "09:30",
    close: "18:30",
  }),
  make({
    slug: "marmara-tedarik",
    name: "Marmara Tedarik",
    category: "b2b",
    subcategory: "Ofis sarf malzemesi",
    city: "İstanbul",
    district: "Şişli",
    address: "Büyükdere Cad. No: 120, Şişli",
    lat: 41.0664,
    lng: 28.9898,
    phone: "0212 555 07 20",
    rating: 4.4,
    reviewCount: 86,
    priceLevel: 2,
    openNow: true,
    summary: "Kâğıt, kartuş ve mutfak sarfı. İstanbul içi ertesi gün sevkiyat.",
    about:
      "Minimum sipariş 2.500 TL’dir. Kurumsal cari hesap için vergi levhası ister. Numune kutusu ilk siparişte ücretsizdir.",
    services: [
      { name: "A4 kâğıt", price: 1450, unit: "koli" },
      { name: "Kartuş seti", price: 3200, unit: "set" },
      { name: "Aylık sarf paketi", price: 18000, unit: "ay" },
    ],
    amenities: ["Ertesi gün", "Cari hesap", "Numune"],
    tags: ["ofis"],
    reviews: reviews([
      ["Ofis Müdürü Kerem", 5, "Eylül 2026", "Kartuş ertesi gün geldi, irsaliye düzgündü."],
      ["Satın Alma Ece", 4, "Mart 2026", "Minimum sipariş küçük ofis için yüksek, paket bölününce makul."],
    ]),
    premium: true,
    responseMinutes: 90,
    founded: 2005,
    photo: "/photos/office.jpg",
    booking: "teklif",
    open: "09:00",
    close: "18:00",
    hoursMode: "weekend-off",
    facts: [
      { label: "Çalışan", value: "48 kişi" },
      { label: "Hizmet bölgesi", value: "İstanbul, Kocaeli" },
      { label: "Sevkiyat", value: "Ertesi iş günü" },
    ],
  }),
  make({
    slug: "ege-ambalaj",
    name: "Ege Ambalaj",
    category: "b2b",
    subcategory: "Ambalaj",
    city: "İzmir",
    district: "Bornova",
    address: "Ankara Cad. No: 210, Bornova",
    lat: 38.4628,
    lng: 27.2186,
    phone: "0232 555 07 10",
    rating: 4.3,
    reviewCount: 64,
    priceLevel: 2,
    openNow: true,
    summary: "Koli, bant ve özel kesim. Numune üç iş günü.",
    about:
      "Baskılı koli minimum 500 adettir. Baskısız stoktan aynı hafta çıkar. İhracat paleti ayrıca konuşulur.",
    services: [
      { name: "Baskısız koli", price: 42, unit: "adet" },
      { name: "Baskılı koli", price: 68, unit: "adet" },
      { name: "Numune", price: 0, unit: "3 gün" },
    ],
    amenities: ["Numune", "Stok", "Palet"],
    tags: ["ofis"],
    reviews: reviews([
      ["Operasyon Naz", 4, "Temmuz 2026", "Stok koli aynı hafta geldi. Baskılı iş ölçüyü tuttu."],
      ["Üretim Can", 4, "Kasım 2025", "Minimum adet net söylendi, sürpriz kalıp ücreti çıkmadı."],
    ]),
    responseMinutes: 240,
    founded: 1999,
    photo: "/photos/warehouse.jpg",
    booking: "teklif",
    open: "08:30",
    close: "18:00",
    hoursMode: "weekend-off",
    facts: [
      { label: "Çalışan", value: "120 kişi" },
      { label: "Minimum baskı", value: "500 adet" },
      { label: "Hizmet bölgesi", value: "Ege" },
    ],
  }),
  make({
    slug: "anadolu-kimya",
    name: "Anadolu Kimya",
    category: "b2b",
    subcategory: "Endüstriyel kimya",
    city: "Ankara",
    district: "Ostim",
    address: "Ostim OSB 1172. Sok. No: 4",
    lat: 39.9698,
    lng: 32.7442,
    phone: "0312 555 07 04",
    rating: 4.2,
    reviewCount: 41,
    priceLevel: 3,
    openNow: false,
    summary: "Temizlik kimyasalı ve yağ çözücü. Güvenlik bilgi formu ile sevk edilir.",
    about:
      "Perakende satış yoktur. Bayi ve fabrika alımı içindir. İlk siparişte güvenlik formu e-posta ile gider.",
    services: [
      { name: "Yağ çözücü", price: 2400, unit: "20 L" },
      { name: "Zemin kimyasalı", price: 1850, unit: "10 L" },
      { name: "Numune", price: 0, unit: "1 L" },
    ],
    amenities: ["Güvenlik formu", "Bayi", "OSB sevkiyat"],
    tags: ["ofis"],
    reviews: reviews([
      ["Bakım Şefi Hakan", 4, "Haziran 2026", "Form eksiksiz geldi. Varil musluğu sağlamdı."],
      ["Satın Alma Selin", 4, "Eylül 2025", "Numune küçük ve yeterliydi. Teklif iki günde döndü."],
    ]),
    responseMinutes: 480,
    founded: 1994,
    photo: "/photos/chemistry.jpg",
    booking: "teklif",
    open: "08:30",
    close: "17:30",
    hoursMode: "weekend-off",
    facts: [
      { label: "Çalışan", value: "36 kişi" },
      { label: "Satış", value: "Yalnızca bayi ve fabrika" },
      { label: "Belge", value: "Güvenlik bilgi formu" },
    ],
  }),
  make({
    slug: "baskent-lojistik",
    name: "Başkent Lojistik",
    category: "b2b",
    subcategory: "Şehirler arası taşıma",
    city: "Ankara",
    district: "Çankaya",
    address: "Konya Yolu No: 250, Çankaya",
    lat: 39.8722,
    lng: 32.8128,
    phone: "0312 555 07 50",
    rating: 4.1,
    reviewCount: 73,
    priceLevel: 2,
    openNow: false,
    summary: "Parsiyel ve komple araç. Ankara çıkışlı ertesi gün batı hattı.",
    about:
      "Fiyat desi ve güzergâha göre teklif edilir. Sigorta poliçe limiti yazılıdır. Hafta sonu çıkış yoktur.",
    services: [
      { name: "Parsiyel", price: 3500, unit: "başlangıç" },
      { name: "Komple araç", price: 28000, unit: "sefer" },
      { name: "Sigorta", price: 0, unit: "poliçe limiti" },
    ],
    amenities: ["Parsiyel", "Yazılı limit", "Takip"],
    tags: ["ofis"],
    reviews: reviews([
      ["Operasyon Baran", 4, "Ağustos 2026", "İzmir hattı ertesi gün vardı. Takip linki çalıştı."],
      ["Depo Müdürü Cem", 4, "Şubat 2026", "Teklif kalem kalem geldi, yakıt farkı ayrıca yazılmıştı."],
    ]),
    responseMinutes: 360,
    founded: 2003,
    photo: "/photos/logistics.jpg",
    booking: "teklif",
    open: "08:30",
    close: "18:00",
    hoursMode: "weekend-off",
    facts: [
      { label: "Çalışan", value: "80 kişi" },
      { label: "Hat", value: "Ankara çıkış, batı illeri" },
      { label: "Çıkış", value: "Hafta içi" },
    ],
  }),
  make({
    slug: "odun-studio",
    name: "Odun Studio",
    category: "dekor",
    subcategory: "Mobilya",
    city: "İstanbul",
    district: "Cihangir",
    address: "Akyol Sok. No: 4, Cihangir",
    lat: 41.0314,
    lng: 28.9848,
    phone: "0212 555 08 04",
    rating: 4.6,
    reviewCount: 122,
    priceLevel: 3,
    openNow: true,
    summary: "Masif sehpa ve konsol. Atölyede numune, teslim üç ile beş hafta.",
    about:
      "Yağ bitiş standarttır. Renk numunesi eve bırakılır. Montaj İstanbul içinde dahildir.",
    services: [
      { name: "Sehpa", price: 18500, unit: "adet" },
      { name: "Konsol", price: 24000, unit: "adet" },
      { name: "Özel ölçü", price: 0, unit: "teklif" },
    ],
    amenities: ["Numune", "Montaj", "Masif"],
    tags: [],
    reviews: reviews([
      ["Elif Odun", 5, "Temmuz 2026", "Sehpa fotoğraftaki damarla geldi. Montaj dikkatliydi."],
      ["Kerem İç", 4, "Aralık 2025", "Süre beş haftayı buldu, ara fotoğraf gönderdiler."],
    ]),
    responseMinutes: 200,
    founded: 2018,
    photo: "/photos/furniture.jpg",
    booking: "teklif",
    open: "11:00",
    close: "19:00",
  }),
  make({
    slug: "han-ic-mimarlik",
    name: "Han İç Mimarlık",
    category: "dekor",
    subcategory: "İç mimarlık",
    city: "İstanbul",
    district: "Nişantaşı",
    address: "Mim Kemal Öke Cad. No: 12, Nişantaşı",
    lat: 41.0498,
    lng: 28.9932,
    phone: "0212 555 08 12",
    rating: 4.8,
    reviewCount: 97,
    priceLevel: 4,
    openNow: true,
    summary: "Daire ve ofis projesi. Ön görüşme ücretli, sözleşmede mahsup edilir.",
    about:
      "Konsept, uygulama çizimi ve şantiye kontrolü ayrı kalemdir. Mobilya satışı yapmaz, üretici eşler.",
    services: [
      { name: "Ön görüşme", price: 4000, unit: "saat" },
      { name: "Konsept", price: 45000, unit: "daire" },
      { name: "Uygulama çizimi", price: 70000, unit: "daire" },
    ],
    amenities: ["Çizim", "Şantiye", "Üretici eşleme"],
    tags: ["luks", "ofis"],
    reviews: reviews([
      ["Aslı Han", 5, "Haziran 2026", "Çizim seti uygulamacıya yetti. Görüşme ücreti sözleşmede düşüldü."],
      ["Mert Ofis", 5, "Ekim 2025", "Ofis planında priz yerleri doğruydu, tadilat uzamadı."],
    ]),
    premium: true,
    responseMinutes: 240,
    founded: 2013,
    photo: "/photos/interior.jpg",
    booking: "teklif",
    open: "10:00",
    close: "18:30",
    hoursMode: "weekend-off",
  }),
  make({
    slug: "lara-bahce",
    name: "Lara Bahçe",
    category: "dekor",
    subcategory: "Peyzaj",
    city: "Antalya",
    district: "Lara",
    address: "Güzeloba Mah. No: 70, Lara",
    lat: 36.8522,
    lng: 30.7604,
    phone: "0242 555 08 70",
    rating: 4.5,
    reviewCount: 108,
    priceLevel: 2,
    openNow: true,
    summary: "Bahçe düzeni, sulama ve mevsimlik bitki. Keşif ücretsizdir.",
    about:
      "Yaz dikimi için sabah saatini önerir. Sulama hattı ayrıca keşifte ölçülür. Bakım aylık sözleşmeye bağlanabilir.",
    services: [
      { name: "Keşif", price: 0, unit: "yerinde" },
      { name: "Bahçe düzeni", price: 35000, unit: "iş" },
      { name: "Aylık bakım", price: 4500, unit: "ay" },
    ],
    amenities: ["Ücretsiz keşif", "Sulama", "Bakım"],
    tags: [],
    reviews: reviews([
      ["Deniz Bahçe", 5, "Nisan 2026", "Sulama hattı ilk yaz sorunsuzdu. Bitki listesini önceden verdiler."],
      ["Okan Yeşil", 4, "Eylül 2025", "Bakım günü aksamadı. Fiyat keşifte netti."],
    ]),
    responseMinutes: 120,
    founded: 2010,
    photo: "/photos/garden.jpg",
    booking: "teklif",
    open: "08:30",
    close: "18:00",
  }),
]

const sectorBusinesses: Business[] = [
  sectorMake({
    slug: "kadikoy-oto-servis",
    name: "Kadıköy Oto Servis",
    category: "oto",
    subcategory: "Oto servis",
    city: "İstanbul",
    district: "Kadıköy",
    lat: 40.9902,
    lng: 29.0274,
    summary: "Periyodik bakım, lastik ve kaporta. Aynı gün randevu açılır.",
    photo: "/photos/repair.jpg",
    booking: "teklif",
    tags: ["acil"],
  }),
  sectorMake({
    slug: "moda-carsi",
    name: "Moda Çarşı",
    category: "alisveris",
    subcategory: "Giyim",
    city: "İstanbul",
    district: "Kadıköy",
    lat: 40.9861,
    lng: 29.0251,
    summary: "Günlük giyim ve ayakkabı. Değişim aynı hafta içinde.",
    photo: "/photos/boutique.jpg",
    booking: "teklif",
  }),
  sectorMake({
    slug: "besiktas-dil",
    name: "Beşiktaş Dil Atölyesi",
    category: "egitim",
    subcategory: "Dil kursu",
    city: "İstanbul",
    district: "Beşiktaş",
    lat: 41.0428,
    lng: 29.0075,
    summary: "İngilizce ve Almanca grup dersi. Deneme dersi ücretsiz.",
    photo: "/photos/office.jpg",
    booking: "randevu",
  }),
  sectorMake({
    slug: "cadde-spor",
    name: "Cadde Spor",
    category: "spor",
    subcategory: "Fitness",
    city: "İstanbul",
    district: "Kadıköy",
    lat: 40.9668,
    lng: 29.0632,
    summary: "Alet salonu, pilates ve PT. Günlük giriş var.",
    photo: "/photos/physio.jpg",
    booking: "randevu",
  }),
  sectorMake({
    slug: "karakoy-sahne",
    name: "Karaköy Sahne",
    category: "eglence",
    subcategory: "Canlı müzik",
    city: "İstanbul",
    district: "Karaköy",
    lat: 41.0229,
    lng: 28.9741,
    summary: "Akşam sahne ve oturma düzeni. Rezervasyon cuma için erken kapanır.",
    photo: "/photos/meyhane.jpg",
    booking: "rezervasyon",
    tags: ["aksam"],
    open: "18:00",
    close: "01:00",
    hoursMode: "all",
  }),
  sectorMake({
    slug: "cankaya-emlak",
    name: "Çankaya Emlak",
    category: "emlak",
    subcategory: "Emlak ofisi",
    city: "Ankara",
    district: "Çankaya",
    lat: 39.9078,
    lng: 32.8544,
    summary: "Konut ve ofis kiralama. Tapu işlemine kadar takip eder.",
    photo: "/photos/konak.jpg",
    booking: "teklif",
  }),
  sectorMake({
    slug: "levent-hukuk",
    name: "Levent Hukuk",
    category: "hukuk",
    subcategory: "Avukatlık",
    city: "İstanbul",
    district: "Levent",
    lat: 41.0816,
    lng: 29.0119,
    summary: "Şirket, iş ve aile hukuku. İlk görüşme randevulu.",
    photo: "/photos/office.jpg",
    booking: "randevu",
  }),
  sectorMake({
    slug: "levent-sigorta",
    name: "Levent Sigorta",
    category: "finans",
    subcategory: "Sigorta",
    city: "İstanbul",
    district: "Levent",
    lat: 41.0794,
    lng: 29.0128,
    summary: "Konut, kasko ve işyeri poliçesi. Hasar dosyası yerinde açılır.",
    photo: "/photos/office.jpg",
    booking: "randevu",
  }),
  sectorMake({
    slug: "kadikoy-taksi",
    name: "Kadıköy Taksi",
    category: "ulasim",
    subcategory: "Taksi",
    city: "İstanbul",
    district: "Kadıköy",
    lat: 40.9908,
    lng: 29.0221,
    summary: "Havalimanı ve şehir içi transfer. Taksometre açık çalışır.",
    photo: "/photos/logistics.jpg",
    booking: "teklif",
    tags: ["acil"],
    hoursMode: "all",
    open: "00:00",
    close: "23:59",
  }),
  sectorMake({
    slug: "moda-vet",
    name: "Moda Vet",
    category: "hayvan",
    subcategory: "Veteriner",
    city: "İstanbul",
    district: "Kadıköy",
    lat: 40.9839,
    lng: 29.0261,
    summary: "Aşı, sterilizasyon ve acil. Kedi köpek kabul eder.",
    photo: "/photos/clinic.jpg",
    booking: "randevu",
    tags: ["acil"],
  }),
  sectorMake({
    slug: "sisli-organizasyon",
    name: "Şişli Organizasyon",
    category: "dugun",
    subcategory: "Düğün",
    city: "İstanbul",
    district: "Şişli",
    lat: 41.0602,
    lng: 28.9878,
    summary: "Nikah, kokteyl ve sahne. Mekân keşfi ücretsiz.",
    photo: "/photos/boutique.jpg",
    booking: "rezervasyon",
  }),
  sectorMake({
    slug: "maslak-yazilim",
    name: "Maslak Yazılım",
    category: "teknoloji",
    subcategory: "Yazılım",
    city: "İstanbul",
    district: "Maslak",
    lat: 41.1086,
    lng: 29.0234,
    summary: "Web, mobil ve entegrasyon. Keşif toplantısı uzaktan da olur.",
    photo: "/photos/electric.jpg",
    booking: "teklif",
  }),
  sectorMake({
    slug: "moda-kres",
    name: "Moda Kreş",
    category: "cocuk",
    subcategory: "Kreş",
    city: "İstanbul",
    district: "Kadıköy",
    lat: 40.9848,
    lng: 29.0281,
    summary: "2–6 yaş grupları. Deneme günü randevuyla.",
    photo: "/photos/breakfast.jpg",
    booking: "randevu",
    tags: ["aile"],
  }),
  sectorMake({
    slug: "lara-sera",
    name: "Lara Sera",
    category: "tarim",
    subcategory: "Sera",
    city: "Antalya",
    district: "Lara",
    lat: 36.8551,
    lng: 30.7682,
    summary: "Fide, toprak ve damla sulama. Bahçe keşfi yazın sabah.",
    photo: "/photos/garden.jpg",
    booking: "teklif",
  }),
  sectorMake({
    slug: "atasehir-yapi",
    name: "Ataşehir Yapı",
    category: "insaat",
    subcategory: "Müteahhit",
    city: "İstanbul",
    district: "Ataşehir",
    lat: 40.9923,
    lng: 29.1227,
    summary: "Kat karşılığı ve kaba inşaat. Proje dosyası keşifte alınır.",
    photo: "/photos/paint.jpg",
    booking: "teklif",
  }),
  sectorMake({
    slug: "organize-guvenlik",
    name: "Organize Güvenlik",
    category: "guvenlik",
    subcategory: "Güvenlik",
    city: "İstanbul",
    district: "İkitelli",
    lat: 41.0792,
    lng: 28.7954,
    summary: "Kamera, alarm ve saha ekibi. Keşif ücretsiz.",
    photo: "/photos/warehouse.jpg",
    booking: "teklif",
  }),
  sectorMake({
    slug: "sisli-ajans",
    name: "Şişli Ajans",
    category: "medya",
    subcategory: "Reklam ajansı",
    city: "İstanbul",
    district: "Şişli",
    lat: 41.0571,
    lng: 28.9798,
    summary: "Marka, sosyal medya ve baskı. Brief toplantısı randevulu.",
    photo: "/photos/office.jpg",
    booking: "teklif",
  }),
  sectorMake({
    slug: "bornova-kombi",
    name: "Bornova Kombi",
    category: "enerji",
    subcategory: "Kombi & doğalgaz",
    city: "İzmir",
    district: "Bornova",
    lat: 38.4622,
    lng: 27.2164,
    summary: "Kombi bakım, doğalgaz tesisatı ve güneş paneli keşfi.",
    photo: "/photos/ac.jpg",
    booking: "teklif",
    tags: ["acil"],
  }),
]

const coveredCategories = new Set(
  [...sampleBusinesses, ...sectorBusinesses, ...zonguldakBusinesses].map((item) => item.category),
)

const PLACE_CYCLE = [
  { city: "İstanbul", district: "Şişli", lat: 41.0601, lng: 28.9874 },
  { city: "Ankara", district: "Çankaya", lat: 39.9012, lng: 32.8594 },
  { city: "İzmir", district: "Konak", lat: 38.4192, lng: 27.1287 },
  { city: "Antalya", district: "Muratpaşa", lat: 36.8874, lng: 30.7051 },
  { city: "Bursa", district: "Osmangazi", lat: 40.1911, lng: 29.0608 },
] as const

const generatedSectorBusinesses: Business[] = seedSectors
  .filter((item) => !coveredCategories.has(item.id))
  .map((item, index) => {
    const place = PLACE_CYCLE[index % PLACE_CYCLE.length]
    return sectorMake({
      slug: `${item.id}-ornek`,
      name: `${place.district} ${item.label}`,
      category: item.id,
      subcategory: item.label,
      city: place.city,
      district: place.district,
      lat: place.lat + ((index % 7) - 3) * 0.006,
      lng: place.lng + ((index % 5) - 2) * 0.006,
      summary: `${item.blurb}. Örnek sektör kaydı; keşif ve randevu bu tarayıcıda durur.`,
      photo: item.photo,
      booking: item.booking,
    })
  })

export const businesses: Business[] = [
  ...sampleBusinesses,
  ...sectorBusinesses,
  ...generatedSectorBusinesses,
  ...zonguldakBusinesses,
]

export function categoryById(id: CategoryId) {
  return allSectors().find((category) => category.id === id) ?? seedSectors[0]
}

export function defaultBooking(category: CategoryId): BookingKind {
  return categoryById(category).booking
}

export function allBusinesses(extra: Business[] = []) {
  const slugs = new Set(extra.map((business) => business.slug))
  return [...extra, ...businesses.filter((business) => !slugs.has(business.slug))]
}
